"""Build B18 self-contained teaching artifacts from canonical code and measured evidence."""
import ast,base64,io,json,re,zipfile
from pathlib import Path
import nbformat as nb
from nbconvert.filters.markdown import markdown2html_mistune as render
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
P=Path(__file__).resolve().parent;R=P.parent;S='b18-context-sufficiency';F=P/'figures/b18'
r=json.loads((P/'evidence/b18/summary.json').read_text());F.mkdir(exist_ok=True)
(R/'assets/b18-evidence.js').write_text('/* Complete measured B18 grid; generated by _build_b18.py. */\nwindow.B18_EVIDENCE='+json.dumps(r,separators=(',',':'))+';\n')
plt.rcParams.update({'font.size':12,'figure.facecolor':'#fafcf9','axes.facecolor':'#fafcf9'})
fig,ax=plt.subplots(figsize=(8,5));pairs=['10+20','10+30','10+40','20+30','20+40','30+40'];x=list(range(6))
ax.bar(x,[60,80,100,100,120,140],color='#28756a',width=.6);ax.axhline(100,color='#a66716',lw=2,label='True total = mean corrected estimate = $100')
ax.set_xticks(x,pairs);ax.set_xlabel('All six equally likely two-event samples');ax.set_ylabel('Corrected total ($)');ax.set_ylim(0,175);ax.legend(loc='upper left',fontsize=10)
ax.set_title('Four credits [10, 20, 30, 40] · N/k = 2',loc='left',weight='bold')
for i,v in enumerate([60,80,100,100,120,140]):ax.text(i,v+3,str(v),ha='center')
fig.tight_layout();fig.savefig(F/'six-pairs.png',dpi=145);plt.close(fig)
fig,ax=plt.subplots(figsize=(8,7));ax.set(xlim=(0,1),ylim=(0,1));ax.axis('off')
def box(x,y,w,h,title,body,color='#e8f2ef'):
 ax.add_patch(FancyBboxPatch((x,y),w,h,boxstyle='round,pad=.01',fc=color,ec='#658c80'))
 ax.text(x+.02,y+h-.025,title,fontsize=13,weight='bold',va='top');ax.text(x+.02,y+h-.082,body,fontsize=11.5,va='top',linespacing=1.45)
def arrow(a,b):ax.annotate('',xy=b,xytext=a,arrowprops=dict(arrowstyle='->',lw=1.8,color='#365e50'))
ax.text(.04,.99,'Two paths from the same legal history',va='top',fontsize=18,weight='bold')
box(.04,.75,.92,.15,'Filter events BEFORE sampling or aggregation','Legal credits [10, 20, 30, 40] → N = 4, total $100\nFuture credit [1,000] is excluded at the cutoff')
box(.04,.45,.43,.20,'Sample two events','Retain [10, 20] → sum $30\nUnseen [30, 40] omitted\nOnly k = 2 records retained')
box(.53,.45,.43,.20,'Complete aggregation','Scan 10 + 20 + 30 + 40\nMonthly sum = $100\nAll N = 4 records processed','#fbefd9')
arrow((.27,.75),(.255,.66));arrow((.73,.75),(.745,.66))
box(.04,.14,.43,.21,'Use the full count N','N/k = 4/2 = 2\nCorrect $30 × 2 = $60\nThis draw: error −$40')
box(.53,.14,.43,.21,'Read the aggregate','One record contains $100\nHistorical sum is exact\nOrder/extremes are lost','#fbefd9')
arrow((.255,.45),(.255,.36));arrow((.745,.45),(.745,.36))
ax.text(.04,.04,'Course information pipeline. No forecast model is trained.\nFull counts and aggregates require access beyond the retained sample.',fontsize=11)
fig.savefig(F/'information-path.png',dpi=145,bbox_inches='tight');plt.close(fig)
fig,axes=plt.subplots(2,1,figsize=(8,8),sharex=True)
for ax,shape in zip(axes,['uniform','concentrated']):
 for arm,color,label in [('sampled','#a66716','Sampled sum'),('corrected','#28756a','N/k corrected')]:
  for seed in [0,1,2]:
   rows=[c for c in r['conditions'] if c['seed']==seed and c['degree']==4096 and c['shape']==shape]
   ax.plot([c['budget'] for c in rows],[c['metrics'][arm]['rmse'] for c in rows],color=color,marker=['o','s','^'][seed],alpha=.75,label=f'{label}, seed {seed}')
 ax.set_title(f'{shape.capitalize()} amounts · degree 4096 · total $1,200',loc='left',weight='bold');ax.set_ylabel('RMSE ($)');ax.grid(alpha=.2)
 ax.set_xscale('log',base=2);ax.set_xticks([8,32,128,512],['8','32','128','512']);ax.set_ylim(bottom=-50)
axes[0].legend(fontsize=9,ncol=2);axes[1].set_xlabel('Context budget (events)')
fig.text(.5,.015,'100 paired draws per point. Three seeds; different vertical scales.\nFull sum and complete monthly aggregation have ≈0 error in both panels.',ha='center',fontsize=10)
fig.tight_layout(rect=[0,.06,1,1]);fig.savefig(F/'degree-errors.png',dpi=145);plt.close(fig)

def figure(name,alt,portable=False):
 src='data:image/png;base64,'+base64.b64encode((F/f'{name}.png').read_bytes()).decode() if portable else f'../labs/figures/b18/{name}.png'
 return f'<figure class="context-figure" tabindex="0" role="region" aria-label="{alt}"><img src="{src}" alt="{alt}"><figcaption>{alt}</figcaption></figure>'
pipe='''<section class="context-board" aria-label="Information pipeline"><h3>From events to an answer</h3><div class="context-flow"><div class="context-step"><strong>Raw events → cutoff and kind filter</strong>[10,20,30,40] are legal credits. Future credit [1,000] is excluded before any count or sum.</div><div class="context-branches"><div class="context-step"><strong>Sample path</strong>4 events → retain [10,20] → sum 30 → add full count N=4 → correct 30 × 4/2 = 60.</div><div class="context-step"><strong>Complete aggregate path</strong>4 events → scan 10 + 20 + 30 + 40 → one monthly record 100 → read exact historical total 100.</div></div><div class="context-step"><strong>What a downstream model can read</strong>Sampled rows omit arbitrary amounts. A full aggregate carries the sum, but loses ordering and extremes. No forecasting model is executed here.</div></div></section>'''
control='''<section class="context-board" data-context-budget><h3>Predict, then change the budget</h3><p>Held fixed: total $1,200, sampling rule, 100 repetitions and all four estimation methods. Values below are saved author measurements.</p><div class="context-controls">'''
for name,values,default in [('seed',[0,1,2],0),('degree',[8,64,512,4096],4096),('shape',['uniform','concentrated'],'concentrated'),('budget',[8,32,128,512],32)]:
 control+=f'<label>{name.capitalize()} <select name="{name}">'+''.join(f'<option value="{v}"'+(' selected' if v==default else '')+f'>{v}</option>' for v in values)+'</select></label>'
control+='''</div><output aria-live="polite">Author measurements are in the table below; enable JavaScript to explore all 96 states.</output><p data-interpret>Compare sampled and corrected RMSE, not only signed bias.</p><button type="button">Reset budget</button><noscript><p>The static table and plot below preserve the key results without JavaScript.</p></noscript></section>'''
results='**Author reference: degree 4,096, concentrated amounts, budget 32.** Each row summarizes 100 draws. Dollar amounts rounded to cents.\n\n| Seed | Sample bias | Sample RMSE | Corrected bias | Corrected RMSE | Aggregate RMSE |\n|---:|---:|---:|---:|---:|---:|\n'
for c in r['conditions']:
 if c['degree']==4096 and c['shape']=='concentrated' and c['budget']==32:
  m=c['metrics'];results+=f"| {c['seed']} | {m['sampled']['bias']:.2f} | {m['sampled']['rmse']:.2f} | {m['corrected']['bias']:.2f} | {m['corrected']['rmse']:.2f} | {m['aggregate']['rmse']:.2f} |\n"
texts={'WORKED':('six-pairs','Exact enumeration: correction averages to $100 but individual totals range from $60 to $140.'),'PIPELINE':('information-path','Course pipeline: time filtering precedes sampling or aggregation; full counts add information.'),'RESULT_FIG':('degree-errors','Measured reconstruction RMSE, three seeds, degree 4096. Concentration makes corrected totals variable.')}

def document(title,body,interactive=False):
 html=render(body).replace('<table>','<div class="context-table" tabindex="0" role="region" aria-label="Scrollable results table"><table>').replace('</table>','</table></div>')
 scripts=['retrieval-pool','retrieval-bank','predict','teachback','temporal-visibility','b18-evidence','context-budget'] if interactive else []
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+'</title><link rel="stylesheet" href="../assets/lesson.css"><link rel="stylesheet" href="../assets/context-budget.css"><link rel="stylesheet" href="../assets/temporal-lesson.css"></head><body><article><nav><a href="../index.html">Course</a> · <a href="../notebooks.html">Notebook gallery</a></nav>'+html+'</article>'+''.join(f'<script src="../assets/{s}.js"></script>' for s in scripts)+'</body></html>'
body=(R/'lessons/content'/f'{S}.md').read_text();lesson=body
for key,(name,alt) in texts.items():lesson=lesson.replace('{{'+key+'}}',pipe if key=='PIPELINE' else figure(name,alt))
lesson=lesson.replace('{{CONTROL}}',control).replace('{{RESULTS}}',results)
(R/'lessons'/f'{S}.html').write_text(document('B18 · Context-window failure and sufficient evidence',lesson,True))
ref='''# B18 · Context sufficiency reference

[Lesson](../lessons/b18-context-sufficiency.html) · [Notebook](../labs/b18-context-sufficiency.ipynb) · [Reproduction contract](../labs/b18-reproduction.md)

| Question | Rule |
|---|---|
| Which events count? | Filter event and availability time by the query cutoff before counting or aggregating |
| What is degree? | Number of eligible related events; declare the event types and time window |
| What is truncated? | Raw sampled sum retains only the observed mass |
| When is N/k correction unbiased? | Uniform sampling without replacement, exact eligible N, k>0 |
| Does unbiased mean exact? | No; concentrate most value in one event to expose variance |
| What is preserved by monthly sums? | The historical sum query; not arbitrary ordering, extremes or future targets |
| What information does aggregation cost? | Access to the complete eligible history, possibly maintained incrementally |
| Which bins are legal inference inputs? | Bins defined from available history, never post-cutoff outcomes |

For fixed historical sum S, E[Sₖ]=(k/N)S. Therefore E[(N/k)Sₖ]=S. Four events [10,20,30,40], k=2: corrected totals [60,80,100,100,120,140], mean 100. For a finite population with variance σ²=mean((x−mean(x))²), Var(Ŝ)=N²(1−k/N)σ²/k × N/(N−1), for N>1. At k=N variance is zero; concentrated amounts increase it.

Bias=mean(prediction−target); RMSE=sqrt(mean((prediction−target)²)). Report both, by historical degree, with every seed. In B18: 24 histories, 96 conditions, 100 draws each, four arms. This is historical reconstruction, not a forecast or a trained-model benchmark.

**Paper audit:** Animus v1 RT main-table positive scores conflict with negative Appendix B entries; best-test captions require selection clarification;474 selected customers are not the complete 10,000-customer test population. [Primary paper](https://arxiv.org/html/2609.00460v1). Paper NOT_RUN / INCOMPLETE_SOURCE_PROTOCOL_GATE. No sign repair or substitute dataset.

**Next experiment:** freeze legal inputs, model selection and complete test population; vary context budget; save sampled IDs; stratify by predeclared historical degree; count the work required to supply N or aggregates. Do not infer broad industry prevalence from a synthetic counterexample.
'''
(R/'reference'/f'{S}.html').write_text(document('B18 · Context sufficiency reference',ref))
# Extract source functions so the learner's three definitions remain live.
source=(P/'relkit/context_b18.py').read_text();tree=ast.parse(source)
parts={n.name:ast.get_source_segment(source,n) for n in tree.body if isinstance(n,ast.FunctionDef)}
testtree=ast.parse((P/'_test_b18.py').read_text());tests=next(ast.get_source_segment((P/'_test_b18.py').read_text(),n) for n in testtree.body if isinstance(n,ast.ClassDef))
packet=io.BytesIO()
with zipfile.ZipFile(packet,'w',zipfile.ZIP_DEFLATED) as z:
 for path in [P/'_reproduce_b18.py',P/'b18-reproduction.md',*(P/'sources/b18').glob('*')]:
  info=zipfile.ZipInfo(str(path.relative_to(P)),date_time=(2026,10,4,0,0,0));info.compress_type=zipfile.ZIP_DEFLATED;z.writestr(info,path.read_bytes())
blob=base64.b64encode(packet.getvalue()).decode()
recap=body.split('## Lab ·')[0]
recap=re.sub(r'<div id="b18-[^"]+"></div>','',recap).replace('<div class="temporal-panel"><div id="b18-time"></div></div>','')
recap=recap.replace('<noscript>','').replace('</noscript>','')
for key,(name,alt) in texts.items():recap=recap.replace('{{'+key+'}}',figure(name,alt,True))
recap=recap.replace('{{CONTROL}}','**Prediction prompt:** will increasing k remove sampling bias, variance, or both? Run the complete grid below to inspect every condition.').replace('{{RESULTS}}',results)
recap=re.sub(r'\]\(\.\./([^)]*)\)',r'](https://avistian.github.io/relational/\1)',recap)
recap=re.sub(r'\]\((b\d[^)]*\.html)\)',r'](https://avistian.github.io/relational/lessons/\1)',recap)
goals={'eligible_history':'Return copied legal credit rows in original order, using day≤cutoff. Reject duplicate IDs and nonfinite times/amounts. Why: filtering after aggregation cannot undo leakage. This fixture assumes event day equals arrival day.', 'corrected_total':'Compute the uniform-sampling total estimator. Validate finite one-dimensional amounts and integer N≥k. Return 0 for N=k=0; reject k=0<N. Why: the full-count assumption must be visible in the interface.', 'stratified_metrics':'Align nonempty degree, prediction and target vectors; reject nonfinite inputs and invalid degrees. Return a dictionary keyed by string degree, with n, signed bias and RMSE. Why: pooled errors can hide a high-degree failure.'}
for solution in [False,True]:
 cells=[]
 def md(x):cells.append(nb.v4.new_markdown_cell(x))
 def py(x):cells.append(nb.v4.new_code_cell(x))
 md(recap)
 md('## Run contract\n\nTier C historical-sum diagnostic. No training/model library is hidden. All load-bearing code is visible below. The three TODOs are called by the final experiment. This notebook uses only NumPy plus Python standard libraries. No files, installs, credentials or repository imports are needed. Tested versions are archived in evidence/b18/environment.json. Predictions below are historical estimates in dollars, never forecasts. Do not use this notebook to claim Animus reproduction.')
 py('# @colab-bootstrap\nimport numpy as np\nimport itertools, unittest, json, gzip\nfrom pathlib import Path')
 md('## PROVIDED · behavioral checks\n\nThe correction check enumerates all six equally likely pairs, independently of the Monte Carlo grid. Time checks include an event exactly on the cutoff. Metric checks use hand-computable errors.')
 py(tests)
 for name,test in [('eligible_history','test_history'),('corrected_total','test_correction'),('stratified_metrics','test_metrics')]:
  md('## '+('SOLUTION' if solution else 'TODO')+' · '+name+'\n\n'+goals[name])
  py(parts[name] if solution else parts[name].split('\n')[0]+'\n    raise NotImplementedError("Implement '+name+'")')
  md('### CHECK · run before continuing')
  py(f"Boundaries('{test}').debug()\nprint('{name}: passed')")
 md('## PROVIDED · fixed histories and complete aggregation\n\nAmounts are USD1200 total. A concentrated history has one USD960 event. Seeds shuffle its position. Extra debit and future credit exercise your filter. The aggregate consumes every filtered row; it is not built from the sampled prefix.')
 py(parts['fixture']+'\n\n'+parts['monthly_total'])
 md('## PROVIDED · paired sampling and reporting\n\nOne random ordering per repetition supplies every budget prefix. Your eligibility, correction and stratification functions are invoked below. All conditions remain in the report; none is selected by its score.')
 py(parts['run_experiment'])
 md('## RUN · complete live grid\n\nThese outputs come from the current kernel. Contrast them with the author reference above. The compressed result preserves all original rows and sampled indices for independent replay.')
 py("report=run_experiment()\nassert len(report['conditions'])==96\nPath('b18-diagnostic.json.gz').write_bytes(gzip.compress(json.dumps(report,sort_keys=True,separators=(',',':')).encode(),mtime=0))\nprint('seed degree shape budget sampled-RMSE corrected-RMSE')\nfor c in report['conditions']:\n    print(c['seed'],c['degree'],c['shape'],c['budget'],round(c['metrics']['sampled']['rmse'],2),round(c['metrics']['corrected']['rmse'],2))")
 md('## EXIT · defend what the calculation establishes\n\nIn 150–200 words derive the correction using inclusion probabilities; explain its variance in the concentrated case; identify the extra full-count access; state the temporal filter and the separate forecasting question. Propose a complete-population degree-stratified falsification test for B24. Ask your teacher for feedback and revisit in 1/7/30 days.')
 py("assert sum(len(c['estimates'][a]) for c in report['conditions'] for a in c['estimates'])==38400\nassert all(f['future_invariant'] for f in report['fixtures'])\nprint('COMPLETE_MECHANISM_DIAGNOSTIC; paper NOT_RUN; learner PENDING_WRITTEN_DEFENSE')")
 md('## Paper-results lane · source audit and explicit refusal\n\nThe embedded source packet supplies the primary paper, dated limited search receipts and complete unresolved 12-configuration RT contract. Audit success authenticates bytes. The paper command deliberately refuses execution and is not an implemented trainer. No claim of complete runnable Animus reproduction is made while original data, code and protocol remain unresolved. Paid compute USD0; all author numerical work shares 3600seconds. Live Colab frontend is not checked by local execution.')
 py("import base64,io,zipfile,subprocess,sys\npacket=Path('b18-source-packet');packet.mkdir(exist_ok=True)\nwith zipfile.ZipFile(io.BytesIO(base64.b64decode("+repr(blob)+"))) as archive:\n    archive.extractall(packet)\naudit=subprocess.run([sys.executable,str(packet/'_reproduce_b18.py'),'--phase','audit'],capture_output=True,text=True,check=True)\nprint(audit.stdout)\nprint((packet/'b18-reproduction.md').read_text())")
 py("RUN_PAPER_REPRO=False\nif RUN_PAPER_REPRO:\n    subprocess.run([sys.executable,str(packet/'_reproduce_b18.py'),'--phase','paper'],check=True)\nelse:\n    print('NOT_RUN / INCOMPLETE_SOURCE_PROTOCOL_GATE')")
 n=nb.v4.new_notebook(cells=cells,metadata=dict(kernelspec=dict(name='python3',display_name='Python3',language='python'),language_info=dict(name='python',version='3.12')))
 nb.write(n,(P/'solutions'/f'{S}.ipynb') if solution else P/f'{S}.ipynb')
print('Built B18 lesson/reference, three figures, student/solution notebooks and measured interaction')
