"""Build the B16 lesson, reference and portable notebooks from measured evidence."""
import ast,base64,io,json,zipfile
from pathlib import Path
import nbformat as nb
from nbconvert.filters.markdown import markdown2html_mistune as render
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
from relkit.partitions_b16 import fixture,incidence_partition
P=Path(__file__).resolve().parent;R=P.parent;S='b16-autograble-graph-selection';E=P/'evidence/b16';F=P/'figures/b16';F.mkdir(parents=True,exist_ok=True)
report=json.loads((E/'diagnostic.json').read_text())
# Interactive controls use the exact archived numeric grid; no hand-copied scores.
small={k:report[k] for k in ['datasets','subsets','selections']}
small['graph_states']={('typed' if typed else 'anonymous')+('-B' if feature else ''):incidence_partition(fixture(),['A'],typed,['B'] if feature else []) for typed in [True,False] for feature in [False,True]}
(R/'assets/b16-evidence.js').write_text('/* Generated by labs/_build_b16.py from finite diagnostic evidence. */\nwindow.B16_EVIDENCE = '+json.dumps(small,separators=(',',':'))+';\n')
plt.rcParams.update({'font.size':12,'axes.titlesize':15,'figure.facecolor':'#fbfcf8','axes.facecolor':'#fbfcf8'})
fig,ax=plt.subplots(figsize=(8,8));ax.set_xlim(0,1);ax.set_ylim(0,1);ax.axis('off')
steps=[('1  Input table and permitted labels','8 training rows: A = 00001111, y = A\nValidation: same A patterns, fresh keys; test held aside'),('2  Project, count, and score each subset','A → blocks {0,1,2,3} / {4,5,6,7}\np(1) = 0 / 1; J = 0 + 0.5 × 0.5 = 0.250'),('3  Compare candidate constructions','Empty: J = 0.427     A: 0.250     unique K: 0.750\nSelect A using validation; freeze before test labels'),('4  Construct the selected incidence graph','8 row nodes → 2 typed A-value nodes; 8 edges\nRows sharing A can exchange information'),('5  Downstream prediction (not run here)','Keep other row features → message passing → row head\nThe paper’s Table 1 measures selection, not GNN training')]
for i,(title,text) in enumerate(steps):
 y=.83-i*.18;ax.add_patch(FancyBboxPatch((.03,y),.94,.14,boxstyle='round,pad=.01',fc='#edf4f1' if i<4 else '#f2ede2',ec='#56817f',linestyle='-' if i<4 else '--'))
 ax.text(.06,y+.105,title,weight='bold',fontsize=13,va='center');ax.text(.06,y+.049,text,fontsize=11.5,va='center',linespacing=1.5)
 if i<4:ax.annotate('',xy=(.5,y-.035),xytext=(.5,y-.012),arrowprops=dict(arrowstyle='->',color='#246879',lw=2))
fig.suptitle('AutoGrable · decide the access before training',fontsize=17);fig.savefig(F/'architecture.png',dpi=150,bbox_inches='tight');plt.close(fig)
fig,axes=plt.subplots(2,1,figsize=(8,7.5),gridspec_kw={'height_ratios':[1.3,1]})
axes[0].axis('off');axes[0].set_title('Same eight rows, different partitions',pad=18)
data=[[r['id'].replace('tr-','r'),r['A'],r['B'],r['K'],r['y']] for r in report['datasets']['signal']['train']]
t=axes[0].table(cellText=data,colLabels=['Row','A','B','Unique K','y = A'],cellLoc='center',loc='center');t.auto_set_font_size(False);t.set_fontsize(12);t.scale(1,1.7)
for i in range(1,9):
 for j in range(5):t[i,j].set_facecolor('#e0f0ec' if i<=4 else '#f4ead4')
axes[1].axis('off');axes[1].set_title('Validation probabilities and the λ = 0.5 score',pad=12)
rows=[]
for cols in [[],['A'],['K']]:
 v=next(x for x in report['subsets'] if x['world']=='signal' and x['penalty']==.5 and x['cols']==cols)
 rows.append([' + '.join(cols) or 'Empty',str(v['sizes']),f"{v['risk']:.3f}",f"{v['omega']:.3f}",f"{v['J']:.3f}"])
t=axes[1].table(cellText=rows,colLabels=['Subset','Block sizes','Brier','Ω','J'],cellLoc='center',loc='center',colWidths=[.15,.34,.16,.16,.16]);t.auto_set_font_size(False);t.set_fontsize(11);t.scale(1,2)
axes[1].text(.5,.02,'Fresh K values are unseen → fall back to P(1)=0.5.\nTraining singleton purity cannot predict unseen keys.',ha='center',va='bottom',transform=axes[1].transAxes,fontsize=12)
fig.tight_layout(pad=1.6);fig.savefig(F/'partitions.png',dpi=150,bbox_inches='tight');plt.close(fig)
fig,axes=plt.subplots(2,1,figsize=(8,6.5),sharex=True)
for ax,p in zip(axes,[.5,1]):
 vals=[next(x for x in report['subsets'] if x['world']=='xor' and x['penalty']==p and x['cols']==s)['J'] for s in [[],['A'],['B'],['A','B']]]
 ax.barh(['Empty','A','B','A + B'],vals,color=['#ae7422','#aac1c5','#aac1c5','#246879']);ax.invert_yaxis();ax.set_xlim(0,.9);ax.set_title(f'XOR, λ = {p}: '+('forward stops before the better pair' if p==.5 else 'empty wins the penalized objective'))
 for i,v in enumerate(vals):ax.text(v+.015,i,f'{v:.3f}',va='center',fontsize=12)
 ax.spines[['top','right']].set_visible(False)
axes[1].set_xlabel('Validation risk + λ × occupancy (lower is better)');fig.tight_layout(pad=1.6);fig.savefig(F/'search.png',dpi=150,bbox_inches='tight');plt.close(fig)
fig,axes=plt.subplots(1,2,figsize=(8,5.2));palette=['#246879','#956312']
for ax,typed in zip(axes,[True,False]):
 ax.set_xlim(-.5,3.5);ax.set_ylim(-.5,3.5);ax.axis('off');ax.set_title('Typed value identity' if typed else 'Anonymous value nodes',fontsize=14)
 for a in [0,1]:
  y=3 if a==0 else 0;vy=2.2 if a==0 else .8
  for j in range(4):
   ax.plot([j,1.5],[y,vy],color='#a1b4b4',zorder=1);ax.scatter([j],[y],s=560,color=palette[a] if typed else palette[0],zorder=2);ax.text(j,y,f'r{4*a+j}',ha='center',va='center',color='white',fontsize=11,zorder=3)
  ax.text(1.5,vy,f'(A, {a})' if typed else 'A type, x=0',ha='center',va='center',fontsize=11,bbox=dict(boxstyle='round,pad=.4',fc='white',ec='#246879'))
 ax.text(1.5,1.5,'2 row classes' if typed else '1 row class',ha='center',va='center',fontsize=13,weight='bold')
fig.suptitle('Identical edges; changed initial value features',fontsize=16);fig.text(.5,.02,'Rows start identical. Node IDs are annotations, not input features.',ha='center',fontsize=12);fig.tight_layout(rect=[0,.07,1,.94]);fig.savefig(F/'identity.png',dpi=150,bbox_inches='tight');plt.close(fig)
architecture='''<section class="ps-board"><h3>Algorithm architecture · the signal example</h3><div class="ps-flow"><div class="ps-step"><strong>1 · Table and legal labels</strong>Eight rows: A = 00001111, y = A. Validation has fresh keys.<small>Test labels stay outside this selection path.</small></div><div class="ps-step"><strong>2 · Project → fit counts → score</strong>A creates {0,1,2,3} and {4,5,6,7}. Training P(1) = 0 and 1.<small>J(A) = 0 + 0.5 × 0.5 = 0.250.</small></div><div class="ps-step"><strong>3 · Choose or decline</strong>Compare empty 0.427, A 0.250, unique K 0.750.<small>Choose A; freeze the decision before test evaluation.</small></div><div class="ps-step"><strong>4 · Materialize the selected graph</strong>8 row nodes → 2 A-value nodes through 8 incidence edges.<small>A=0 and A=1 define the shared communication routes.</small></div><div class="ps-step ps-model"><strong>5 · Downstream model · not run here</strong>Unexpanded row features → message-passing layers → row prediction head.<small>This path explains the full system. RQ1/Table 1 tests selection only.</small></div></div></section>'''
rowtable='<table><thead><tr><th>Row</th><th>A</th><th>B</th><th>K</th><th>y</th></tr></thead><tbody>'+''.join(f'<tr><td>r{i}</td><td>{r["A"]}</td><td>{r["B"]}</td><td>{r["K"]}</td><td>{r["y"]}</td></tr>' for i,r in enumerate(report['datasets']['signal']['train']))+'</tbody></table>'
penalty='<label>Penalty λ <select name="penalty"><option value="0">0</option><option value="0.5" selected>0.5</option><option value="1">1</option></select></label>'
options=''.join('<option value="'+','.join(x['cols'])+'"'+(' selected' if x['cols']==['A'] else '')+'>'+(' + '.join(x['cols']) or 'Empty')+'</option>' for x in report['subsets'] if x['world']=='signal' and x['penalty']==.5)
partition='<section class="ps-board" data-partition-selection><h3>What does this subset remember?</h3>'+rowtable+'<label>Selected columns <select name="subset">'+options+'</select></label>'+penalty+'<button type="button">Reset partition</button><div class="ps-blocks" data-blocks></div><output aria-live="polite">A: risk 0; occupancy 0.5; J=0.250 at λ=0.5.</output><p class="ps-baseline" data-baseline>Empty J=0.427 at λ=0.5.</p><noscript><p>A groups four zeros and four ones. K makes eight singleton blocks but validation uses new keys: p=0.5 and J=0.750.</p></noscript></section>'
search='''<section class="ps-board" data-greedy-search><h3>Trace a search, then compare with the oracle</h3><label>Label rule <select name="world"><option value="xor">XOR interaction</option><option value="signal">Signal y=A</option><option value="null">Null within blocks</option></select></label>'''+penalty+'''<label>Search method <select name="method"><option value="forward">Forward additions</option><option value="backward">Backward removals</option><option value="exhaustive">Exhaustive oracle</option></select></label><button type="button">Reset search</button><div class="ps-lattice" data-lattice></div><p class="ps-path" data-path>∅ → stop</p><output aria-live="polite">XOR at λ=0.5: forward stops empty; A+B has lower J.</output><p class="ps-baseline">Baseline: XOR, λ=0.5. Forward stops at J=0.427; exhaustive and backward reach A+B at J=0.354. Highlight marks the selected subset; the entire candidate grid stays visible.</p><noscript><p>At λ=1, empty J=0.604 beats A+B J=0.707. Null at λ=0.5 selects empty with all three methods.</p></noscript></section>'''
graph='''<section class="ps-board" data-incidence-boundary><h3>Keep the edges; change the visible features</h3><label>Value-node input <select name="identity"><option value="typed">Expose typed identities</option><option value="anonymous">Only type and zero feature</option></select></label><label>Row-local input <select name="features"><option value="none">Erase all row features</option><option value="B">Retain unexpanded B</option></select></label><button type="button">Reset graph</button><div data-graph></div><output aria-live="polite">Typed A identities with erased row features: two row classes.</output><p class="ps-baseline">Baseline: same 8 rows and 8 incidence edges; typed value identities; no row features. Row colours show the computed stable partition.</p><noscript><p>Hide literal value identities: one row class. Keep typed identities and add row B: four classes. Labels y never enter the graph.</p></noscript></section>'''
results='| World · λ=0.5 | Search | Selected | Validation J | Test Brier |\n|---|---|---|---:|---:|\n'
for x in report['selections']:
 if x['penalty']==.5:results+=f'| {x["world"]} | {x["method"]} | {" + ".join(x["selected"]) or "∅"} | {x["J"]:.3f} | {x["test_brier"]:.3f} |\n'
def document(title,text,interactive=False):
 scripts=['retrieval-pool','retrieval-bank','predict','teachback','b16-evidence','partition-selection'] if interactive else []
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+'</title><link rel="stylesheet" href="../assets/lesson.css"><link rel="stylesheet" href="../assets/partition-selection.css"></head><body><article><nav><a href="../index.html">Course</a> · <a href="../reference/curriculum.html#research-bridge">Research bridge</a></nav>'+render(text).replace('<table>', '<div class="ps-table" role="region" aria-label="Scrollable data table" tabindex="0"><table>').replace('</table>', '</table></div>')+'</article>'+''.join('<script src="../assets/'+x+'.js"></script>' for x in scripts)+'</body></html>'
body=(R/'lessons/content'/f'{S}.md').read_text()
for key,value in dict(ARCHITECTURE=architecture,PARTITIONS=partition,SEARCH=search,GRAPH=graph,RESULTS=results).items():body=body.replace('{{'+key+'}}',value)
(R/'lessons'/f'{S}.html').write_text(document('B16 · AutoGrable: selecting or declining a graph',body,True))
ref='''# B16 · Construction selection reference

**Decision:** choose communication routes only when validation gain pays for fragmentation. An empty graph still permits row-local prediction.

| Term | Operational meaning |
|---|---|
| Projection partition | Rows share a block iff all selected column values agree |
| Block predictor | Training label proportion in that cell; unseen cells use the training marginal |
| Occupancy Ω | Sum of square roots of training block sizes, divided by training row count |
| J(S) | Validation risk + λΩ; smaller is better |
| Forward / backward | Start empty / full; accept one-column changes with improvement > τ |
| Search gap | Returned J minus minimum J across every candidate |
| Abstention | Select empty; no cross-row edges, not no prediction |
| 1-WL | Refine colours using own colour and typed neighbor-colour multiset |

**Eight rows:** Ω(one block)=0.354, Ω(two blocks of four)=0.5, Ω(singletons)=1. Signal y=A at λ=0.5: J(empty)=0.427, J(A)=0.250, J(K)=0.750. Unseen keys cannot reuse training labels.

**XOR:** at λ=0.5, A/B alone cost more than empty but A+B costs less. Forward gets stuck; backward reaches the pair. At λ=1, empty wins the objective. This does not establish downstream GNN performance.

**Lemma boundary:** projection = structural row colours only with row features erased and typed value identities exposed. Full row features can refine it; anonymous value nodes can merge it. Blocks are not connected components.

**Information:** fit counts on training labels → select on validation → freeze → evaluate test. Test labels never influence construction. Candidate features are fixed before validation.

'''+results+'''

**Source audit:** pinned backward search cannot drop its last column; training/frequency counts differ from validation counts; value-node x is zero. The finite scorer matches 144 aligned primitive comparisons, not whole-source behavior. Table 1 requires 400 selection runs; missing driver/settings leave `INCOMPLETE_SOURCE_PROTOCOL_GATE`, execution `NOT_RUN`. Cloud $0; learner `PENDING_WRITTEN_DEFENSE`.

[Lesson](../lessons/b16-autograble-graph-selection.html) · [Lab](../labs/b16-autograble-graph-selection.ipynb) · [Contract](../labs/b16-reproduction.md) · [Paper](https://arxiv.org/html/2608.11431v1)
'''
(R/'reference'/f'{S}.html').write_text(document('B16 · Construction selection reference',ref))
code=(P/'relkit/partitions_b16.py').read_text();tree=ast.parse(code);functions={n.name:ast.get_source_segment(code,n) for n in tree.body if isinstance(n,ast.FunctionDef)}
imports='\n'.join(ast.get_source_segment(code,n) for n in tree.body if isinstance(n,(ast.Import,ast.ImportFrom)))
def chunk(names):return '\n\n'.join(functions[n] for n in names)
def figure(name,caption):return '![B16 '+name+'](data:image/png;base64,'+base64.b64encode((F/(name+'.png')).read_bytes()).decode()+')\n\n'+caption
archive=io.BytesIO()
with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED) as z:
 for p in sorted((P/'sources/b16').rglob('*')):
  if p.is_file() and '__pycache__' not in p.parts and p.suffix!='.pyc':z.write(p,str(p.relative_to(P)))
 for p in [P/'_reproduce_b16.py',E/'paper-status.json',E/'source-audit.json',E/'table1-targets.json',P/'b16-reproduction.md']:
  z.write(p,str(p.relative_to(P)))
blob=base64.b64encode(archive.getvalue()).decode()
checks={
'block_predict':"tr=[dict(id='a',A=0,y=0),dict(id='b',A=0,y=1),dict(id='c',A=1,y=1)]\nassert block_predict(tr,[dict(A=0),dict(A=1),dict(A=2)],['A'])==[.5,1,2/3], 'Seen cells need train proportions; unseen needs train marginal'\nassert block_predict(tr,[dict(A=99)],[])==[2/3]\nprint('Block prediction CHECK passed')",
'occupancy':"assert abs(occupancy([8])-1/math.sqrt(8))<1e-12\nassert occupancy([4,4])==.5\nassert occupancy([1]*8)==1\ntry: occupancy([0])\nexcept ValueError: pass\nelse: raise AssertionError('Reject nonpositive block sizes')\nprint('Occupancy CHECK passed')",
'select_columns':"tr=[dict(id=f'tr-{i}',A=i//4,B=(i//2)%2,y=(i//4)^((i//2)%2)) for i in range(8)]\nva=[dict(r,id=r['id'].replace('tr','va')) for r in tr]\nassert select_columns(tr,va,['A','B'],.5,'forward')['selected']==[]\nassert select_columns(tr,va,['A','B'],.5,'backward')['selected']==['A','B']\nassert select_columns(tr,va,['A','B'],.5,'exhaustive')['selected']==['A','B']\nassert select_columns(tr,va,['A','B'],1,'backward')['selected']==['A','B'], 'Backward also has a local trap at lambda=1'\nassert select_columns(tr,va,['A','B'],1,'exhaustive')['selected']==[]\nnull_train=[dict(r,y=i%2) for i,r in enumerate(tr)]\nnull_valid=[dict(r,id=r['id'].replace('tr','va')) for r in null_train]\nassert select_columns(null_train,null_valid,['A','B'],.5,'backward')['selected']==[], 'Null case must permit removing the last column'\nprint('Search CHECK passed')"}
goals={
'block_predict':'Fit only on train: group by the selected projection, divide positive labels by block count, and use the overall train proportion for unseen queries. Empty columns give one block. Query labels must never be read. Call the provided row/column validation helpers. **Why:** a unique training key must not reveal a new row’s label.',
'occupancy':'Validate a nonempty list of positive integer sizes; return sum(sqrt(size))/sum(size). **Why:** perfect training purity can be purchased by fragmenting every row. Derive the one-block and singleton extremes before coding.',
'select_columns':'Return a dictionary with selected, J and trace. Score with score_subset; enumerate with subsets for the exhaustive method. Break exhaustive ties by fewer columns then lexical order (within tolerance); greedy moves inspect sorted candidates and require improvement > tolerance. Start empty/full for forward/backward; permit removing the last column. Record considered moves and accepted states. **Why:** the same objective can have different search outcomes. Pseudocode: initialize → score every one-column neighbor → choose the best → accept only strict improvement → repeat.'}
for solution in [False,True]:
 cells=[]
 def md(s):cells.append(nb.v4.new_markdown_cell(s))
 def py(s):cells.append(nb.v4.new_code_cell(s))
 md('''# B16 · AutoGrable: selecting or declining a graph

**Skill:** choose a column-induced graph using permitted training/validation information, including the empty construction. [Lesson](https://avistian.github.io/relational/lessons/b16-autograble-graph-selection.html).

**Mirror scope:** implement the block predictor, occupancy score, exhaustive oracle, Algorithm 1 search, typed incidence constructor and actual colour refinement from [AutoGrable v1](https://arxiv.org/html/2608.11431v1). Three live TODOs with immediate CHECKs. Full visible code, Python standard library, no repository imports or package installs needed. Complete finite diagnostic only; the 400-run Adult Table 1 reproduction is blocked by missing source protocol. No GNN training is necessary for RQ1, and none is claimed here.

## Concept recap

A partition groups rows agreeing on selected columns. Selecting A with four zeros and four ones creates two blocks. The block predictor estimates the fraction of training labels equal to one in each block. A new validation key uses the training marginal, not a memorized label.

The occupancy Ω=sum(sqrt(n_b))/n penalizes tiny blocks. Eight rows in one block give 0.354; two equal blocks give 0.5; eight singleton blocks give 1. J is validation risk plus λΩ. We use binary Brier risk, the average of (p−y)², as a course choice. At λ=0.5, signal A scores 0.250 and unseen keys score 0.750.

Forward search only adds a column when J improves; backward removes columns. XOR requires A and B together. A or B alone can worsen J, trapping forward search before the useful pair. Empty is a legitimate output: rows may still have features even with no cross-row edges.

A graph’s initial features matter. With erased row features and typed value identities, stable row colours equal the projection groups. Hide value identity and symmetric stars collapse. Keep other row features and the full graph can distinguish more rows. Labels are not input features.

**Frozen data:** 8 train + 8 validation + 8 test rows per world; A=i//4, B=(i//2)%2, unique split-specific K. Signal y=A; XOR y=A XOR B; null y=i%2. Three λ values (0,0.5,1), all 8 subsets, three methods. Exact exhaustive ties favor fewer columns; greedy ties stop. IDs are disjoint, though A/B patterns deliberately repeat. This is a designed finite distribution, not a sampled benchmark. Float64 comparisons use tolerance 1e-12.

**Prediction before running:** which subset wins in each world at λ=0.5? Write your answer, then compare with the measured table after completing your code.
''')
 md('## Algorithm architecture\n\n'+figure('architecture','End-to-end example for signal y=A. The dashed downstream stage is explanatory and NOT_RUN. RQ1/Table 1 measures selected columns, not GNN predictive performance.'))
 py('# @colab-bootstrap\n# Python standard library only. No installs, downloads or repository imports.\n'+imports)
 md('## PROVIDED · input contracts and exact projection\n\nThese helpers keep label/id out of the feature set and reject unsupported values. Exact typed tuples avoid silently mixing missing-value sentinels with real categories.')
 py(chunk(['validate_rows','check_columns','projection']))
 md(figure('partitions','Course signal fixture. Probabilities fit training blocks; validation uses fresh K values. Decimals are rounded to three places.'))
 for task in ['block_predict','occupancy']:
  md('## '+('SOLUTION' if solution else 'TODO')+' · '+task+'\n\n'+goals[task]);py(functions[task] if solution else functions[task].split('\n')[0]+'\n    raise NotImplementedError("Complete '+task+'")');md('### CHECK · '+task+'\n\nRun now; fix the input/counting error before continuing.');py(checks[task])
 md('## PROVIDED · score each candidate (Eq.1)\n\nBrier loss is the course default. The optional 0–1 and clipped-log losses permit narrow upstream scoring comparisons; they do not establish the loss used in Table 1. The scorer calls your live block_predict and occupancy functions.')
 py(chunk(['loss_value','score_subset','subsets']))
 md('## '+('SOLUTION' if solution else 'TODO')+' · select_columns\n\n'+goals['select_columns']);py(functions['select_columns'] if solution else functions['select_columns'].split('\n')[0]+'\n    raise NotImplementedError("Complete select_columns")');md('### CHECK · search path and abstention\n\nReject implementations that return a fixed answer, choose test scores, or stop backward at one column.');py(checks['select_columns'])
 md(figure('search','Finite XOR scores with Brier loss. At λ=0.5 the pair is the best objective but forward cannot reach it. At λ=1 abstention is the objective optimum. The vertical order is fixed across panels.'))
 md('## PROVIDED · build the graph and run colour refinement\n\nEach row connects to its selected typed values. A signature contains own colour plus a multiset of typed neighbor colours. Intern signatures injectively until no further splitting occurs. In this finite refinement, equal block count implies stabilization because old colours are retained. Never compare arbitrary colour IDs across separately interned graphs.')
 py(chunk(['incidence_graph','color_refinement','incidence_partition']))
 md(figure('identity','Actual edge pattern for A selected. Both panels erase row features. Changing initial value identity changes the row partition even though edges are identical. Row numbers are annotations, not model features.'))
 md('## PROVIDED · complete finite generator and frozen evaluation\n\nThe generator has no randomness and no hidden optimizer. The evaluation pipeline selects before test labels are scored. All 256 binary test-label vectors are interventions: labels may change reported loss, but never selected columns or probabilities. These functions call your live implementations.')
 py(chunk(['fixture','evaluate_frozen','run_experiment']))
 md('## RUN · full finite grid\n\nExpected coverage: 72 subset scores, 27 selections, 24 graph checks and 256 test-label interventions. The following table is produced by your live functions, not a pasted author result.')
 py("report=run_experiment()\nassert len(report['subsets'])==72 and len(report['selections'])==27\nassert len(report['graph_checks'])==24 and len(report['test_interventions'])==256\nassert all(r['unchanged'] for r in report['test_interventions'])\nprint(f\"{'World':9} {'Method':11} {'Selected':12} {'J':>7} {'Test Brier':>11}\")\nfor row in report['selections']:\n    if row['penalty']==.5:\n        selected='+'.join(row['selected']) or 'empty'\n        print(f\"{row['world']:9} {row['method']:11} {selected:12} {row['J']:7.3f} {row['test_brier']:11.3f}\")\nimport json\nfrom pathlib import Path\nPath('b16-diagnostic.json').write_text(json.dumps(report,indent=2,sort_keys=True)+'\\n')")
 md('## EXIT · explain the mechanism\n\nWrite 150–200 words: separate objective failure from search failure in XOR; explain unseen-key fallback; state the lemma’s two feature assumptions; explain why no test label may choose the graph. Include one source discrepancy and its implication. Ask the teacher for feedback. Revisit after 1/7/30 days. Author execution is not learner mastery.')
 py("assert report['feature_boundary']==dict(typed=[[0,1,2,3],[4,5,6,7]],anonymous=[list(range(8))],full=[[0,1],[2,3],[4,5],[6,7]])\nprint('B16-PARTITION-SELECTION: COMPLETE_FINITE_DIAGNOSTIC')\nprint('B16-AUTOGRABLE-TABLE1: INCOMPLETE_SOURCE_PROTOCOL_GATE; execution NOT_RUN')\nprint('Learner: PENDING_WRITTEN_DEFENSE')")
 md('''## Paper-results lane · inspect the complete pinned release

**Named target:** Table 1, 5 task families × 2 encodings × 2 directions × 2 penalties × 10 seeds = 400 selection runs. Metrics are exact-recovery and recall percentages. Full target grid is retained in the contract. No fresh Table 1 run has occurred.

**Missing:** authenticated Adult/preprocessing and sample identity, seed/split recipe, planted column/value/threshold/binarization and balancing rules, actual loss/tolerance. The generic income example cannot substitute for the synthetic family generator.

**Demonstrated source differences:** backward search stops at one column; train uses train-frequency counts while validation uses union counts; actual value-node x is zero while the lemma assumes typed identity. Optional per-ID/random-hash value encoders exist in the TabArena model and are off by default; the zero-feature counterexample concerns the audited graph configuration. Source defaults are not historical experiment records. Narrow 144-case score parity on 0–1/log loss does not fix these differences. The course deliberately uses bounded Brier loss and permits backward removal to empty.

The following packet contains the complete release, paper, source hashes, executable guarded preflight, measured source audit and contract. The preflight runs from this notebook without repo access. It has no cloud dispatch. Turning on the last cell authenticates sources, then refuses the underspecified paper run. This is an executable gate, not a completed benchmark runner. The original experimental driver must be recovered before that can change.

Budget: initial USD0 cloud, USD10 total ceiling, paid stop USD8/reserve USD2. Local author numerical cap 3600 aggregate seconds; portable learner reruns are a separate execution. Other paper benchmarks NOT_RUN, historical identity NOT_ESTABLISHED, live Colab NOT_CHECKED.
''')
 py("import base64,io,zipfile,subprocess,sys\npacket=Path('b16-source-packet');packet.mkdir(exist_ok=True)\narchive=zipfile.ZipFile(io.BytesIO(base64.b64decode("+repr(blob)+")))\narchive.extractall(packet)\ncheck=subprocess.run([sys.executable,str(packet/'_reproduce_b16.py'),'--phase','audit'],capture_output=True,text=True,check=True)\nprint(check.stdout)")
 md('### Read the released selector beside your implementation\n\nThese are unmodified source files from the pinned release. The example above implements the paper’s backward-to-empty search; locate the conflicting stopping condition below. Full graph models/trainers are in the extracted packet; they are not required for RQ1.')
 # Source scrollability, not an opaque archive as the only access to the release algorithm.
 for sourcefile in ['selection.py','utils.py']:
  md('#### Pinned upstream '+sourcefile+'\n\n```python\n'+(P/'sources/b16/autograble/src/autograble'/sourcefile).read_text()+'\n```')
 py("RUN_PAPER_REPRO=False\nif RUN_PAPER_REPRO:\n    subprocess.run([sys.executable,str(packet/'_reproduce_b16.py'),'--phase','paper'],check=True)\nelse:\n    print('Paper reproduction OFF: recover the original Table 1 driver and resolve discrepancies first.')")
 n=nb.v4.new_notebook(cells=cells,metadata=dict(kernelspec=dict(name='python3',display_name='Python 3',language='python'),language_info=dict(name='python',version='3.12')))
 target=P/'solutions'/f'{S}.ipynb' if solution else P/f'{S}.ipynb';nb.write(n,target)
print('Built B16 lesson, reference, four figures and portable notebooks')
