"""Build L057 with live, visible implementations and portable computation figures."""
from _lesson_depth import enrich_notebook
import ast,base64,json,os
from pathlib import Path
from urllib.parse import urlsplit
import nbformat as nbf
from bs4 import BeautifulSoup
from _build_l049 import mdtext
from _colab import bootstrap_cells
ROOT=Path(__file__).resolve().parent;SLUG='0057-cross-family-ensembling'
def piece(file,name):
 s=(ROOT/file).read_text();return next(ast.get_source_segment(s,n) for n in ast.parse(s).body if isinstance(n,(ast.FunctionDef,ast.ClassDef)) and n.name==name)
def build(solution=False):
 cells=[]
 def md(s):cells.append(nbf.v4.new_markdown_cell(s.strip()))
 def code(s):cells.append(nbf.v4.new_code_cell(s.strip()))
 def fig(name,caption):md('!['+caption+'](data:image/png;base64,'+base64.b64encode((ROOT/'figures/l057'/f'{name}.png').read_bytes()).decode()+')\n\n'+caption)
 soup=BeautifulSoup((ROOT.parent/'lessons'/f'{SLUG}.html').read_text(),'html.parser')
 def section(name):
  el=BeautifulSoup(str(soup.find('section',id=name)),'html.parser').find('section')
  for n in el.find_all(['figure','script']):n.decompose()
  for n in el.find_all('div',id=True):n.decompose()
  for a in el.find_all('a',href=True):
   u=urlsplit(a['href'])
   if not u.scheme and u.path:a['href']=os.path.relpath((ROOT.parent/'lessons'/u.path).resolve(),ROOT)+('#'+u.fragment if u.fragment else '')
  md(mdtext(el))
 def task(name,signature,description):
  md(description);code('# TODO — '+name+'\n'+(piece('relkit/cross_ensemble.py',name) if solution else signature+'\n    raise NotImplementedError("Implement the operation described above")'))
 md('''# Lab 057 · Cross-family ensembling

**Skill:** build an OOF probability stack and evaluate a validation-selected combination against a validation-selected single model. [Lesson](../lessons/0057-cross-family-ensembling.html) · [Reference](../reference/cross-family-ensembling.html) · [Contract](l057-reproduction.md).

**Before input:** explain why an OOF fold cannot also be its predictor's early-stopping set; why test-selected best-single is an oracle; and why more folds do not mean more independent datasets. Write your answers before proceeding.

PROVIDED = read/run; TODO = implement; CHECK = immediate feedback; EXIT = submit evidence and interpretation. Four live TODO functions drive both the OOF trainer and complete three-family audit. Allow 45–60 minutes learning plus training time. No GPU or checkpoint download is needed for the main worksheet: it trains a small tree/TabM example and audits committed author XGB/TabM/TabICL predictions. The gated fresh-three-family/scale-up track downloads a 108 MB checkpoint and uses the exact same visible code.

**Mirror scope:** OOF construction + Caruana greedy combiner from scratch; the known L054 TabM source is visible below. XGB is a provided base library; TabICL is a provided pretrained API baseline, not an architecture/pretraining reproduction. Small numeric OpenML tables are Tier A substitutes for TabArena's 51-task roster. Fixed recipes, 3 folds, log loss and fold-averaged TabICL differ from the paper. Exact Figure 6 verdict: **INCOMPARABLE**. Model seeds 0/1/2; row/outer/fold seed57. Version, dataset hash, row IDs and checkpoint hash are recorded in the author evidence. The synthetic four-row example only isolates a mechanism.''')
 for c in bootstrap_cells():cells.append(nbf.v4.new_markdown_cell(c['source']) if c['cell_type']=='markdown' else nbf.v4.new_code_cell(c['source']))
 md('''## Concept recap

A binary prediction is the probability of class 1. A convex mixture uses weights at least zero that sum to one, so its output stays a valid probability. Mixing hard predictions discards information. Log loss is negative mean log probability assigned to the correct class; lower is better.

OOF predictions are generated by models fitted without the predicted row. Keep that row out of learned preprocessing, early stopping and in-context labels too. One row gets one OOF probability per family; row order must be restored when folding ends. Test predictions instead average the fitted fold models within each family.

A greedy combiner tries adding each family's OOF probabilities to the running sum. Pick the lowest-loss trial average and allow replacement. A selected sequence [A,A,B,A] means weights [.75,.25]. Retain the best OOF prefix of the fixed-length search, then freeze weights before test evaluation. OOF labels train this second-level model; OOF loss is not its unbiased evaluation.

In the synthetic example below, A and B each have loss .8574, but their opposite error patterns give a 50/50 mixture loss .5978. Duplicating A cannot help. This is evidence about these four probabilities, not evidence that arbitrary family mixtures improve every real dataset.''')
 fig('diversity','Synthetic mechanism: equal individual quality, complementary row errors. The mixture uses probabilities, not logits.')
 section('architecture');fig('architecture','Complete local OOF stack: train-only transforms/context, aligned held-out rows, frozen weights, and test-fold averaging.')
 code('''# PROVIDED — setup and versions
import os,sys,json,hashlib,math,importlib.metadata,time
from pathlib import Path
import numpy as np
import pandas as pd
import torch
from torch import nn
from sklearn.model_selection import train_test_split,StratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from scipy.stats import rankdata,friedmanchisquare,studentized_range,t
from threadpoolctl import threadpool_limits
from xgboost import XGBClassifier
from IPython.display import display
for p in (Path.cwd(),Path.cwd()/'labs',Path.cwd().parent):
    if (p/'relkit').is_dir():
        ROOT=p.resolve();os.chdir(ROOT);sys.path.insert(0,str(ROOT));break
else:raise RuntimeError('Start in the course workspace or run Colab bootstrap')
from relkit.data import load_tier_a,SPECS,CACHE
print({p:importlib.metadata.version(p) for p in ['numpy','scipy','scikit-learn','torch','xgboost']})
torch.set_num_threads(1)''')
 task('train_indices','def train_indices(fold_ids, heldout):','''## TODO 1 · Exclude the predicted fold
**Goal:** return original row positions whose fold ID differs from heldout. **Why:** no row should train its own base predictor. **Hint boundary:** preserve row identity; do not return fold IDs or a shuffled subset.''')
 code('''# CHECK — noncontiguous fold rows and complement
np.testing.assert_array_equal(train_indices(np.array([0,1,0,2,1]),1),[0,2,3])
assert len(set(train_indices(np.array([0,1,0,2,1]),1)) & {1,4})==0
print('PASS: fold complement')''')
 task('write_oof','def write_oof(matrix, seen, indices, predictions):','''## TODO 2 · Assemble aligned predictions
**Goal:** mutate a [rows,families] matrix and integer coverage vector. Scatter predictions to original integer indices and increment coverage. **Why:** stacking mismatched rows can pass shape checks while learning nonsense. Reject repeated/out-of-range/noninteger indices, previously filled rows, wrong shapes and nonfinite or out-of-range probabilities. **Hint boundary:** perform validation before mutation. Return value is not used.''')
 code('''# CHECK — shuffled arrival, duplicate and invalid probability guards
z=np.full((4,2),np.nan);seen=np.zeros(4,int)
write_oof(z,seen,np.array([2,0]),np.array([[.2,.4],[.1,.3]]))
np.testing.assert_allclose(z[[0,2]],[[.1,.3],[.2,.4]])
for ix,pred in [(np.array([0]),np.array([[.2,.4]])),(np.array([1]),np.array([[np.nan,.3]]))]:
    try:write_oof(z,seen,ix,pred)
    except ValueError:pass
    else:raise AssertionError('Duplicate or invalid OOF prediction accepted')
assert seen.tolist()==[1,0,1,0]
print('PASS: original row alignment and coverage protection')''')
 task('blend','def blend(predictions, weights):','''## TODO 3 · Combine probabilities
**Goal:** map [rows,models] predictions and [models] weights into [rows] probabilities. **Why:** class/row alignment and convex weights are the prediction contract. Reject wrong dimensions, nonfinite or out-of-range probabilities, negative/nonfinite weights and a weight sum unequal to one (allow floating tolerance). **Hint boundary:** do not renormalize invalid inputs silently.''')
 code('''# CHECK — actual arithmetic and convexity
np.testing.assert_allclose(blend(np.array([[.2,.8],[.4,.6]]),[.75,.25]),[.35,.45])
for w in ([-.1,1.1],[1,1],[np.nan,0]):
    try:blend(np.ones((2,2)),w)
    except ValueError:pass
    else:raise AssertionError('Invalid weights accepted')
print('PASS: convex prediction')''')
 section('selection');fig('selection','Synthetic trial mixtures: compare candidate losses at each step, then keep the best prefix.')
 code('# PROVIDED — numeric log loss\n'+piece('relkit/cross_ensemble.py','binary_loss'))
 task('greedy_select','def greedy_select(oof, y, steps=40):','''## TODO 4 · Fit the combiner
**Goal:** return (best_weights, history) using only OOF probabilities/labels. Start empty; at each positive integer step evaluate adding every column to the sum, choose minimum log loss (first-column ties within 1e-12), update counts/sum, and retain the first best prefix. Validate inputs using blend and binary_loss. **Why:** replacement converts counts into weights without test-label access. **Hint boundary:** divide a candidate sum by the number of selected members including the new one. History entries contain step, chosen, chosen_loss and losses (all candidate losses); no test argument belongs here.''')
 code('''# CHECK — replacement, best single and complementary members
y0=np.array([0,1]);z0=np.array([[.1,.8],[.9,.2]])
w,trace=greedy_select(z0,y0,7);np.testing.assert_array_equal(w,[1,0]);assert len(trace)==7
z1=np.array([[.1,.8],[.8,.1],[.9,.2],[.2,.9]]);y1=np.array([0,0,1,1])
w,tr=greedy_select(z1,y1,3);np.testing.assert_allclose(w,[.5,.5]);assert tr[-1]['chosen_loss']>tr[1]['chosen_loss']
assert binary_loss(y1,blend(z1,w))<=min(binary_loss(y1,z1[:,j]) for j in range(2))
print('PASS: replacement and best-prefix retention; test improvement is not guaranteed')''')
 md('''## PROVIDED · The known TabM branch, visible again
L054's numeric TabM-mini is reproduced below in coherent parts. Each layer shares its main weights across internal members; member-specific adapters introduce diversity. The final probability averages member softmax outputs. These definitions are used by the trainer below; the new lesson task is OOF combination, not rebuilding the L054 architecture. XGBoost and pretrained TabICL are provided base-model integrations.''')
 for names in [('kaiming_','sign_pm1','batchensemble_linear','packed_head'),('member_mean_loss','ensemble_predict'),('MLP','BatchEnsembleLinear','PackedHead'),('TabM',)]:
  code('# PROVIDED — L054 / TabM paper §3\n'+'\n\n'.join(piece('relkit/tabm.py',n) for n in names))
 md('''## PROVIDED · Training and evaluation protocol
Each fit uses only its supplied rows. Trees and neural epochs are fixed before evaluation, so there is no early-stopping leak. The optional TabICL branch supplies only these fitting rows as labeled context. It uses a released checkpoint; its internal architecture is an explicit API exception for this ensemble lesson.

Read oof_library closely: your train_indices and write_oof are invoked in its actual fold loop. Test probabilities use the very same models, averaged within each family. evaluate_library calls your greedy_select and blend; the best-single family is chosen by OOF loss before any test scoring.''')
 from relkit.cross_experiment import PRESETS,CHECKPOINT
 code('# PROVIDED — fixed presets\nPRESETS='+repr(PRESETS)+'\nCHECKPOINT='+repr(CHECKPOINT))
 for name in ['load_binary','fit_predict','oof_library','evaluate_library','summarize','run_suite']:
  code('# PROVIDED — visible '+name+'\n'+piece('relkit/cross_experiment.py',name))
 md('''## Run your OOF pipeline on real rows
This fresh CPU smoke run uses diabetes, two known families, seed0, cap360, three folds, 8epochs/40trees. It checks the implementation; it is not the main evidence table. Predict whether the greedy stack must improve test log loss before running. The full three-family author analysis follows.''')
 code('''# PROVIDED — fresh fit driven by your four functions
fresh=run_suite('smoke',names=('diabetes',),seeds=(0,),include_tfm=False,output_dir='data/cache/l057-student')
display(pd.DataFrame([fresh['rows'][0]['errors']]))
audit=json.loads(Path('data/cache/l057-student/diabetes-0-folds.json').read_text())
assert all(not set(f['fit_rows']) & set(f['held_rows']) for f in audit)
assert sorted(i for f in audit for i in f['held_rows'])==list(range(len(fresh['datasets']['diabetes']['dev_ids'])))
print('PASS: real-row disjointness and exact-once OOF coverage')''')
 md('''## Audit all three families on all three datasets
The following are **author-reference predictions**, not fits from your current kernel. They come from 81 fold-family fits/context constructions: 3 datasets × 3 seeds × 3 folds × 3 families. Hashes protect exact arrays; the contract records fit recipes and checkpoint identity. Recompute their weights and test scores using your functions. Do not use test labels to change those weights.

Report mean±sample SD for each dataset and a paired stack-minus-OOF-best interval. These intervals condition on fixed rows/folds; they do not measure generalization over new datasets. A zero-width interval from an identical selected model is not proof of population equivalence.''')
 code('''# PROVIDED — hash-verified complete archived audit
provenance=json.loads((ROOT/'_data_l057.json').read_text());reference=json.loads((ROOT/'_verify_l057_results.json').read_text())
rows=[]
for entry in provenance['predictions']:
    path=ROOT/entry['path'];assert hashlib.sha256(path.read_bytes()).hexdigest()==entry['sha256']
    with np.load(path) as q:
        row=evaluate_library(q['oof'],q['test'],q['y'],q['yt'],reference['families'],reference['config']['steps'])
    row.update(dataset=entry['dataset'],seed=entry['seed']);rows.append(row)
    original=next(r for r in reference['rows'] if r['dataset']==entry['dataset'] and r['seed']==entry['seed'])
    np.testing.assert_allclose(row['weights'],original['weights'],atol=1e-12)
    np.testing.assert_allclose(list(row['errors'].values()),list(original['errors'].values()),atol=1e-12)
summary=summarize(rows)
for dataset,table in summary['table'].items():
    print(dataset);display(pd.DataFrame(table).T[['mean','sd','ci95']])
print('Mean ranks:',summary['mean_ranks'],'Friedman p:',summary['friedman_p'],'Nemenyi CD:',summary['nemenyi_cd'])
Path('data/cache/l057-student-audit.json').write_text(json.dumps(summary,indent=2))
print('PASS: all 9 three-family runs match from your live functions')''')
 fig('results','Author-reference evidence: every seed shown; bars are sample SD, not confidence intervals.')
 fig('uncertainty','Author-reference paired seed intervals and dataset-balanced ranks; three datasets provide little power.')
 md('''## Interpretation checkpoint
Before inspecting the source report again, answer: Which dataset improves against the OOF-selected single? Does any worsen? Is that the same as beating every individually measured test score? Why can an ensemble assign weight to a weaker test model? What extra matched-budget experiment is needed to compare cross-family and within-family diversity?''')
 code('''# EXIT — submit this artifact AND your written interpretation
exit_artifact={'fresh_training':'two-family diabetes smoke; one seed',
 'archived_audit':'three families, three datasets, three seeds; not current-kernel fits',
 'summary':summary,'paper_verdict':'INCOMPARABLE','larger_run':'NOT_RUN unless gate below executed'}
Path('data/cache/l057-exit.json').write_text(json.dumps(exit_artifact,indent=2))
print('Saved data/cache/l057-exit.json. Add the OOF coverage, weights, identities and interpretation required above.')''')
 md('''## Required next experiment · fresh three-family stack and larger run
The curriculum target includes XGB + TabM + TabICL. The author has measured the small three-family track; now run it with your implementation when ready, then run the larger preset. Installation is separate so the main notebook does not download unused foundation-model dependencies. `RUN_THREE_FAMILY=False` deliberately skips the download/training; it does not count as completing this track.

Choose `lab` to regenerate the archived recipe (3folds, cap750, one TabICL view). Choose `closer` for 5folds, cap2000, TabM k32/width128/64epochs, 300trees, four TabICL views. Both use three seeds. GPU recommended for closer; do not claim a known Colab runtime before measuring it. Artifacts go into a persistent directory you choose; free Colab storage is ephemeral.

For unattended GPU execution: `modal run --detach modal/l057_paper_repro.py --preset closer` from the repository root, then `modal volume get relational-l057 closer-results.json .`. The cloud operator uses the canonical completed functions; the cell below uses **your live notebook functions**. This is a larger comparison, not a faithful TabArena paper preset. Full Figure 6 requires its original task/method roster, predictions, metric, folds, selection policy and evaluator; see the contract.''')
 code('''# PROVIDED — deliberate install/training gate (off by default)
RUN_THREE_FAMILY=False
PRESET='closer' # 'lab' regenerates the author recipe
if RUN_THREE_FAMILY:
    import subprocess
    subprocess.check_call([sys.executable,'-m','pip','install','-r',str(ROOT/'requirements-l057-tfm.txt')])
    from _fetch_l057 import fetch
    device='cuda' if torch.cuda.is_available() else 'cpu'
    larger=run_suite(PRESET,include_tfm=True,device=device,checkpoint=fetch(),output_dir='data/cache/l057-live-'+PRESET)
    Path('data/cache/l057-live-'+PRESET+'-results.json').write_text(json.dumps(larger,indent=2))
    print(larger['summary']);print('INCOMPARABLE to Figure 6; compare the new paired gaps to the author lab.')
else:
    print('Fresh three-family / larger student run NOT_RUN. Author measured lab evidence is separate.')''')
 md('''## Conclusion ledger
| Bucket | Status | Meaning |
|---|---|---|
| Your fresh CPU run | RUN after successful cells | Two-family one-dataset smoke; implementation check |
| Author three-family experiment | RUN; audit MATCH after CHECK | Three small real datasets, three seeds, frozen recipes |
| Source selector check | MATCH on five fixtures | Pinned selector with local loss adapter; tie rules differ |
| TabArena Figure 6 | CITED / INCOMPARABLE | Original full benchmark not regenerated |
| Larger student / Modal track | NOT_RUN until executed | More compute and changed recipe, still not paper fidelity |
| Browser / live Colab / publication | See delivery record | Local execution and image payload checks do not verify those frontends |

Ask the tutor about any failed CHECK or conclusion you cannot justify. Submit your EXIT plus prose for feedback. Completing the notebook is evidence; reading an author table alone is not mastery.''')
 nb=enrich_notebook(nbf.v4.new_notebook(cells=cells,metadata={'kernelspec':{'name':'python3','display_name':'Python 3','language':'python'},'language_info':{'name':'python','version':'3.12'}}),57);return nb
if __name__=='__main__':
 for sol in [False,True]:
  dest=ROOT/('solutions' if sol else '.')/(SLUG+'.ipynb');dest.parent.mkdir(exist_ok=True);nbf.write(build(sol),dest);print(dest)
