"""Record completed evidence and remaining gaps; never infer paper parity from checks."""
import hashlib,json,platform
from pathlib import Path
P=Path(__file__).resolve().parent;m=json.loads((P/'_sources_l093.json').read_text())
files=['_verify_l093_results.json','_audit_l093_results.json','_teaching_l093_results.json','_baseline_l093_results.json','_capacity_l093_results.json','_cs_resource_l093_results.json','_execution_l093_results.json','_portable_l093_results.json','_delivery_l093_results.json']
records={name:{'sha256':hashlib.sha256((P/name).read_bytes()).hexdigest(),'status':json.loads((P/name).read_text())['status']} for name in files}
paper={'status':'NOT_RUN','target':m['target'],'source_revision':m['source_revision'],'publication_source_revision':m['publication_source_revision'],'data':m['cs_data'],'full_paper_parity':'NOT_ESTABLISHED','historical_parity':'INCOMPARABLE','completed_CS_fits':0,'planned_CS_fits':5,'local_blocker':json.loads((P/'_cs_resource_l093_results.json').read_text()),'gpu_blocker':{'image_build':'PASS','GPU_execution':'NOT_RUN','error':'Please add a payment method to use A10G GPU functions.','command':'.venv/bin/modal run modal/l093_paper_repro.py --preset smoke'},'remaining':['Complete five CS fits with provisioned memory/GPU','Establish CS snapshot and feature provenance against paper','Resolve printed/2020/modern operator and checkpoint differences','Replay historical runtime and seeds if recoverable','Full Med/OAG and remaining tasks, baselines and ablations'],'local_evidence':records}
(P/'_paper_l093_results.json').write_text(json.dumps(paper,indent=2)+'\n')
p=P/'reproductions/execution_evidence.json';ledger=json.loads(p.read_text());ledger['l093']={'date':'2026-09-20','status':'TEACHING_AND_OPERATOR_EVIDENCE_ONLY','named_target':paper['target'],'CS_target':'NOT_RUN','full_paper_parity':'NOT_ESTABLISHED','historical_parity':'INCOMPARABLE','source_revision':m['source_revision'],'data_hashes':{k:m[k]['sha256'] for k in ['nn_data','cs_data']},'artifacts':records,'commands':['.venv/bin/python labs/_verify_l093.py','.venv/bin/python labs/_run_l093.py --preset teaching --seeds 0 1 2 --arms hgt rgcn hgt_no_rte --output labs/_teaching_l093_results.json','.venv/bin/python labs/_baseline_l093.py','.venv/bin/python labs/_audit_l093.py','.venv/bin/python labs/_execute_l093.py --teaching','/tmp/l093-portable/bin/python labs/_portable_l093.py','.venv/bin/python labs/_delivery_l093.py'],'rejected_inferences':['Perfect NN MRR is not useful-generalization proof; train-frequency baseline also reaches1.0','A passed full-width NN update is not a CS result','Exact operator/sampler parity is not historical experiment reproduction'],'blockers':[paper['gpu_blocker']['error'],'CS loader exceeded explicit10GiB virtual-address guard'],'live_colab':'NOT_CHECKED','deployment':'NOT_CHECKED'};p.write_text(json.dumps(ledger,indent=2)+'\n');print('L093 evidence recorded')
