"""Lesson-specific teaching contracts for the L058–L070 builder."""
SLUGS={58:'surveys-meta-benchmarks',59:'validation-set-overfitting',60:'broad-model-comparison',
61:'prior-data-fitted-networks',62:'tabpfn-v1',63:'synthetic-scm-prior',64:'tabpfn-v2',
65:'tabpfn-query-embeddings',66:'tabicl-column-row-attention',67:'local-pfn-retrieval-finetuning',
68:'pfns-under-temporal-shift',69:'tabpfn-open-environment-failures',70:'foundation-model-checkpoint'}
TITLES={58:'Read a benchmark without inheriting its bias',59:'When validation becomes training',60:'A baseline comparison you can defend',
61:'Learn Bayesian prediction across tasks',62:'Trace the original TabPFN',63:'What a synthetic causal prior encodes',
64:'Trace TabPFN v2 across both table axes',65:'Extract embeddings without their own labels',66:'How TabICL builds and uses context',
67:'Retrieve locally, then test adaptation',68:'Teach a PFN about changing mechanisms',69:'Find the broken prediction contract',70:'Defend your foundation-model baseline'}
PRIMARY={58:('TALENT Sections 4–5 and 8','https://arxiv.org/html/2407.00956v3'),59:('Cawley and Talbot 2010','https://jmlr.org/papers/v11/cawley10a.html'),
60:('TabArena and TabReD protocols','https://arxiv.org/html/2506.16791v1'),61:('Transformers Can Do Bayesian Inference','https://arxiv.org/html/2112.10510v7'),
62:('TabPFN v1','https://arxiv.org/html/2207.01848v6'),63:('TabPFN v1 prior','https://arxiv.org/html/2207.01848v6'),
64:('Nature TabPFN v2','https://www.nature.com/articles/s41586-024-08328-6'),65:('A Closer Look at TabPFN v2, Section 6','https://arxiv.org/html/2502.17361v1'),
66:('TabICL, Sections 3–4','https://arxiv.org/html/2502.05564v1'),67:('Retrieval & Fine-Tuning for In-Context Tabular Models, final NeurIPS 2024','https://papers.nips.cc/paper_files/paper/2024/file/c40daf14d7a6469e65116507c21faeb7-Paper-Conference.pdf'),
68:('Drift-Resilient TabPFN, final NeurIPS 2024','https://papers.nips.cc/paper_files/paper/2024/file/b2e2774c8e76afe191b5bf518f5cb727-Paper-Conference.pdf'),69:('Realistic Evaluation of TabPFN v2 in Open Environments','https://arxiv.org/html/2505.16226v1'),
70:('TabPFN-3 technical report and historical controls','https://arxiv.org/abs/2605.13986')}
WIDGET={58:'ranks',59:'selection',60:'ranks',61:'posterior',62:'mask',63:'scm',64:'cost',65:'folds',66:'inducing',67:'neighbors',68:'time',69:'classes',70:'cost'}
QUIZ={
58:('You retain only tasks where XGBoost beat the other models. What population does the new mean rank describe?', ['The selected task subset','The original task population','Every future deployment table'],0,'Outcome selection changes the evaluation population; the selected rank is not an independent estimate of broad advantage.'),
59:('You select the best of 256 pure-noise candidates on validation. What independent test error do you expect?', ['Approximately 0.25 error','Approximately 0.50 error','Approximately 0.75 error'],1,'Selection finds lucky validation noise. Independent test labels carry no signal, so expected error remains 0.50.'),
60:('Three datasets each have random and temporal splits and three model seeds. How many dataset blocks belong in each regime-specific rank test?', ['Three dataset blocks','Six dataset blocks','Eighteen dataset blocks'],0,'Average seeds within each dataset, then use three datasets separately in each regime. Split regimes share underlying tasks.'),
61:('Under Beta(1,1), your context has three successes and one failure. What is the next-success posterior prediction?', ['Probability = 3/4','Probability = 1/2','Probability = 2/3'],2,'The posterior is Beta(4,2); its predictive mean is 4/6, distinct from the empirical rate 3/4.'),
62:('With fixed preprocessing and context-only keys, you append an unrelated query. Which existing query path changes?', ['Its context attention changes','Neither computation path changes','Its residual features change'],1,'The existing query retains the same features and context keys/values. The new query cannot enter its attention memory.'),
63:('In the fixed-noise chain V0 → V1 → V2, you remove the V1 → V2 edge. Which nodes can change?', ['Only node V0','Only node V1','Only node V2'],2,'The intervention changes the child equation. Its ancestors keep their original structural equations and exogenous noise.'),
64:('Ignore target tokens and hold N fixed. Doubling F changes N F² feature-attention score elements by which factor?', ['A factor of two','A factor of four','A factor of eight'],1,'Within-row feature attention pairs every feature with every feature. Doubling both feature axes gives four times as many scores.'),
65:('Row 8 belongs to held-out fold 2. Where can its target enter when constructing its cross-fitted query embedding?', ['Only the context label input','Only the query label input','Neither encoder label input'],2,'The row is absent from context and its query target is hidden. Its target is used later for supervised head training.'),
66:('With C=N=500 and m=16, how many scalar attention scores do both inducing stages use for one column/head?', ['16,000 score elements','250,000 score elements','500,000 score elements'],0,'The two stages require mC+Nm = 8,000+8,000 scores. This omits other TabICL stages and projection costs.'),
67:('Retrieval changes context IDs while every checkpoint tensor stays identical. Which operation has occurred?', ['Context selection has occurred','Gradient adaptation has occurred','Offline pretraining has occurred'],0,'A changed context is an inference input change. Fine-tuning requires an optimization step that changes pretrained parameters.'),
68:('Zeroing time in a trained drift model changes which experimental factor?', ['The inference input representation','The sampled pretraining distribution','The original checkpoint initialization'],0,'The weights and their training history stay fixed. A separately pretrained NoT2V model is needed for the paper ablation.'),
69:('Four correct-class probabilities are .8; one required class is unsupported. With epsilon 1e−12, approximately what is all-row mean log loss?', ['Approximately 0.223 nats','Approximately 1.609 nats','Approximately 5.705 nats'],2,'The mean is [−4 ln(.8) − ln(1e−12)]/5 ≈ 5.705. Dropping the unsupported row would hide the failure.'),
70:('You add three measured models without changing existing predictions. Which existing quantity can change?', ['Their saved test predictions','Their reconstructed test losses','Their within-dataset model ranks'],2,'Ranks depend on the declared comparison pool. Existing predictions and losses remain fixed when extra arms are added.')}
PREDICT={
58:('Does choosing datasets by XGBoost advantage independently establish that advantage?','No, selection biases the evaluation population.'),
59:('Must searching more noise candidates improve independent test performance?','No, validation selects lucky noise; test performance remains chance in expectation.'),
60:('Do two split regimes of one dataset create two independent datasets?','No, the underlying task is shared; keep regimes separate.'),
61:('Must a learned posterior approximation extrapolate beyond its training context sizes?','No, a learned finite-range approximation need not preserve the analytic rule outside that range.'),
62:('May an unrelated query become a context key for another query in this mask?','No, only labeled context rows supply keys in this inductive path.'),
63:('Does a causal pretraining generator identify the true causal graph of a deployment table?','No, the synthetic prior is an assumption over tasks, not an identification result.'),
64:('Does passing an attention-mask check establish Nature-v2 accuracy reproduction?','No, it checks an operator boundary, not pretrained weights, data, tuning or scores.'),
65:('Can you treat a labeled-context embedding as an equivalent unlabeled-query embedding?','No, their information roles differ because one can contain its own target.'),
66:('Does inducing-point column attention make every stage of TabICL linear in rows?','No, the final dataset-level context attention retains a quadratic component.'),
67:('Does retrieving a new context prove that the PFN weights were fine-tuned?','No, retrieval changes inputs; fine-tuning requires measured parameter updates.'),
68:('Does supplying time teach a PFN how mechanisms change?', 'Time supplies an index; pretraining on changing task mechanisms teaches a conditional prediction rule.'),
69:('Can unsupported-class rows be dropped while claiming all-row deployment accuracy?','No, dropping them changes the evaluated population and hides coverage failures.'),
70:('Can a v2 score fill an unrun v3 entry in a current-model checkpoint?','No, version identity is part of the model and the missing arm must stay visible.')}
ARCH={
61:[('SAMPLED TASK','theta ~ Beta(1,1)','one latent probability per task'),('CONTEXT','s successes, f failures','query label drawn from same theta'),('SUFFICIENT STATISTICS','[s,f] / 32  →  [B,2]','no information about theta is lost here'),('LEARNED PREDICTOR','2 → 32 → 32 → 1','GELU hidden layers; sigmoid output'),('QUERY LOSS','BCE(q, y_query)','pretraining changes weights; inference fixes them')],
62:[('INPUT', 'context X [C,F], y [C]; query X [Q,F]', 'fit numeric transforms on context only'), ('ROW TOKENS', 'scale K/k, pad to 100; project to 512', 'add scalar label embedding only to context'), ('CONTEXT ATTENTION', '4 heads; all receivers read C context keys', 'no query self edges or other query keys'), ('REPEATED BLOCKS', '12 postnorm blocks; GELU FFN 512 → 1024 → 512', 'all 25,821,706 pretrained parameters mapped'), ('OUTPUT', 'query states → 10 logits; retain K active classes', 'undo class shifts; mean view logits; softmax at T=0.8')],
64:[('INPUT ENCODERS','feature cells/groups + target token','local hidden array [B,C+Q,F+1,D]'),('FEATURE ATTENTION','reshape [B*N,F+1,D]','each row mixes its own feature/target tokens'),('SAMPLE ATTENTION','reshape [B*(F+1),N,D]','each feature reads context rows only'),('REPEAT + RESIDUALS','feature → sample → feed-forward','official IDs/grouping/encoders omitted locally'),('OUTPUT','query target states [B,Q,D]','classification head → probabilities')],
65:[('OUTER TRAIN ROWS','partition into K folds','preserve original row identity'),('FOLD CONTEXT','other K−1 folds with labels','fixed pretrained v2 encoder'),('QUERY REPRESENTATIONS','held-out fold gets unknown labels','scatter [N,D] back to original order'),('HEAD TRAINING','fit scaler + logistic regression','validation selects regularization'),('EVALUATION','average fold-context test embeddings','frozen head; test labels score only')],
66:[('COLUMN INPUT','scalar values → U [N,D]','same column encoder across features'),('INDUCING ATTENTION','I [m,D] reads U_context → M','all U read M; training-only memory'),('CELL + ROW ENCODING','W(U)*x+B(U) → row Transformer','4 CLS states concatenate → width 512 (paper)'),('DATASET ICL','add context-label representation','12-layer learner in original paper config'),('OUTPUT','query states → MLP → probabilities','v1.1 reference checkpoint; key-part local mirror')],
67:[('MEMORY','train-only scaled feature rows','labels must be available; IDs retained'),('RETRIEVE','squared distances → eligible top k','query/anchor identity excluded in episodes'),('PRETRAINED PFN','labeled local context + query features','same historical v1 checkpoint in all arms'),('ADAPTATION ONLY','near-anchor disjoint context/query split','query cross entropy updates copied weights'),('OUTPUT / SELECTION','validation selects adaptation step','frozen state predicts untouched test rows')],
68:[('SECOND-ORDER PRIOR','sample time to correlated functional-edge shifts','sparse selected causal relationships'),('DATA GENERATOR','shared changing mechanism plus row noise','earlier context and later query domains'),('NUMERIC / TIME INPUT','two-feature groups plus 100 learned time coordinates','context-fitted normalization; projected group identifiers'),('PRETRAINED PFN','12 alternating feature and asymmetric row-attention blocks','D192, H6, FF768, context labels only'),('PREDICTION','query target token to 10-class head','released frozen weights; one-view local protocol')]}

# name, module, signature, objective. Full solutions are extracted from canonical code.
TASKS={
58:[('parse_talent', 'talent_audit_l058', 'def parse_talent(path):', 'Return two aligned DataFrames (means, reported SDs). Preserve original row labels, reject duplicate IDs/headers and malformed nonmissing values. Recognize empty, dash, em dash, NA, N/A and nan+nan as missing. Strip Markdown emphasis and accept scientific notation and + or ± separators.'), ('rank_matrix', 'talent_audit_l058', 'def rank_matrix(scores, higher_is_better):', 'Return [datasets, methods] average-tie ranks starting at one, lower rank meaning better. Reject nonfinite, empty or non-2D inputs and require an explicit Boolean direction. This function must rank only the supplied columns.'), ('dataset_bootstrap', 'talent_audit_l058', 'def dataset_bootstrap(matrix, draws=2000, seed=58):', 'Return [2, methods] percentile bounds at .025 and .975 by averaging resampled whole dataset rows. Use a local default_rng(seed), validate finite nonempty 2D input and positive integer draws.'), ('select_tiny', 'talent_audit_l058', 'def select_tiny(seen_ranks, size, trials=1000, seed=58):', 'Propose trials subsets of size unique rows using default_rng(seed).choice(..., replace=False); sort their indices. Minimize MAE between subset and full-column means, keeping the first minimum. Return indices, first_indices, seen_mae and best_so_far (one incumbent loss per proposal). Validate finite nonempty 2D input and positive integer size/trials; size cannot exceed row count.'), ('method_holdout', 'talent_audit_l058', 'def method_holdout(scores, higher_is_better, seen, size, trials=1000, seed=58):', 'Validate a complete score matrix and a unique nonempty integer seen-index list with a nonempty complement. Rank seen columns by themselves, call select_tiny, then rank unseen columns independently. Return seen, unseen, selection, and random/selected dictionaries each containing seen_mae and unseen_mae.')],
59:[('choose_validation', 'validation_audit_l059', 'def choose_validation(errors):', 'Return the first index of the minimum finite loss. Reject empty, nonfinite and non-vector inputs.'), ('loo_residuals', 'validation_audit_l059', 'def loo_residuals(alpha, inverse_diagonal):', 'Return the paper §2.1 residual vector using the augmented inverse diagonal. Validate finite aligned nonempty vectors and strictly positive diagonal entries.'), ('select_krr', 'validation_audit_l059', 'def select_krr(x, y, candidates):', 'Fit each declared configuration using krr_fit, compute mean squared live loo_residuals, choose with live choose_validation, and return (chosen_model, index, all_losses). Reject an empty list.'), ('nested_predictions', 'validation_audit_l059', 'def nested_predictions(x, y, folds, candidates):', 'Return a length-n prediction array and per-fold trace. For each integer fold, call live select_krr on complement rows, predict held rows, and scatter in original order. Trace fields: fold, fit_ids, held_ids, selected, selection_mse. Validate target/fold lengths and at least two integer folds.'), ('paired_difference', 'validation_audit_l059', 'def paired_difference(left, right):', 'Return n, mean, sd (ddof=1), mc_se, and t95 for left−right. Reject nonfinite, non-vector, mismatched or fewer-than-two observations. Use scipy.stats.t.ppf.')],
60:[('validate_partitions', 'comparison_l060', 'def validate_partitions(ids):', 'Accept exactly train, val and test, each a nonempty one-dimensional integer ID array; reject duplicates within and across parts. Return True.'), ('choose_validation', 'comparison_l060', 'def choose_validation(errors):', 'Return the first index of the smallest finite loss in a nonempty one-dimensional sequence.'), ('score_predictions', 'comparison_l060', 'def score_predictions(y,p,regression):', 'Require aligned finite nonempty vectors and a Boolean task flag. For regression compute RMSE. Otherwise validate labels in {0,1}, probabilities in [0,1], clip with float64 machine epsilon, and compute binary log loss.'), ('aggregate_panel', 'comparison_l060', 'def aggregate_panel(records,datasets,arms,seeds):', 'Reject duplicate, missing or extra dataset/arm/seed keys against the explicit roster. Average errors over seeds first, then use average-tie rankdata. Return datasets, seeds, arms, details, mean_ranks, dataset_ranks, friedman_p, nemenyi_cd and uncertainty. Each detail includes dataset, arm, mean, sd, seed_values, conditional_t95 and seconds. SD and interval are None for one seed.'), ('paired_effect', 'comparison_l060', 'def paired_effect(records,dataset,arm,baseline):', 'For one task and two distinct arms, require matching unique seed sets with at least two pairs. Return n, mean, sd, t95, differences and direction for arm minus baseline, sorted by seed.')],
61:[('sample_gp','pfn_l061_v2',"def sample_gp(batch,total,features,generator,lengthscale=.6,noise=1e-4,device='cpu'):",'Draw all context and query labels jointly from the declared Gaussian-process prior.'),('gp_posterior','pfn_l061_v2','def gp_posterior(x,context_y,n,lengthscale=.6,noise=1e-4):','Compute the exact noisy posterior predictive mean and variance, including empty context.'),('context_attention_mask','pfn_l061_v2',"def context_attention_mask(total,n,device='cpu'):",'Allow context senders and each query self edge while blocking all other query senders.'),('attention_mix','pfn_l061_v2','def attention_mix(q,k,v,mask):','Apply masked scaled dot-product attention to the projected values.'),('riemann_nll','pfn_l061_v2','def riemann_nll(logits,y,borders):','Compute normalized predictive density with uniform interior intervals and weighted half-normal tails.')],
62:[('normalize_context', 'tabpfn_l062_v2', 'def normalize_context(x,n):', 'Fit sample moments on labeled context rows and clamp standardized values.'), ('scale_pad', 'tabpfn_l062_v2', 'def scale_pad(x,max_features=100):', 'Apply the historical K/k feature scaling and pad to the fixed input width.'), ('attention_mix', 'tabpfn_l062_v2', 'def attention_mix(q,k,v):', 'Mix context values with scaled attention weights; queries supply no keys.'), ('postnorm_update', 'tabpfn_l062_v2', 'def postnorm_update(h,attention_output,block):', 'Compute both residual additions and post-addition norms with the GELU feed-forward branch.'), ('aggregate_views', 'tabpfn_l062_v2', 'def aggregate_views(logits,shifts,classes,temperature=.8):', 'Undo class rotations, average logits and apply the historical temperature before softmax.')],
63:[('sparse_weights', 'scm_l063_v2', 'def sparse_weights(raw,mask,dropout,first=False):', 'Apply the selected historical independent-edge dropout scaling and preserve the first-layer exception.'), ('propagate', 'scm_l063_v2', 'def propagate(causes,weights,biases,noises,activation):', 'Evaluate the initial affine layer and later activation-affine-noise layers in order using the shared task parameters.'), ('select_nodes', 'scm_l063_v2', 'def select_nodes(values,feature_nodes,target_node):', 'Select distinct observed feature nodes and a separate target from the generated latent values.'), ('rank_labels', 'scm_l063_v2', 'def rank_labels(target,bound_indices,permutation):', 'Use sampled task target bounds, strict comparisons and class relabeling to construct multiclass targets.'), ('posterior_weights', 'scm_l063_v2', 'def posterior_weights(log_prior,log_context,log_query_x):', 'Normalize finite-world posterior weights using context evidence and the observed query feature likelihood.')],
64:[('group_features', 'tabpfn_l064_v2', 'def group_features(x,group_size=2):', 'Pad and group adjacent features while preserving row identity and group membership.'), ('encode_targets', 'tabpfn_l064_v2', 'def encode_targets(y,total_rows):', 'Encode observed context labels and the missing-query target role using the released target mapping.'), ('attention_mix', 'tabpfn_l064_v2', 'def attention_mix(q,k,v):', 'Compute scaled attention weights and mix values, including broadcast shared keys and values.'), ('row_attention', 'tabpfn_l064_v2', 'def row_attention(h,n,attention):', 'Apply ordinary multi-head attention to context and first-head-key/value attention to queries, keeping queries out of memory.'), ('postnorm_update', 'tabpfn_l064_v2', 'def postnorm_update(h,update):', 'Add the sublayer update before non-affine LayerNorm with the released epsilon.')],
65:[('extract_target_states', 'query_embeddings_l065_v2', "def extract_target_states(hidden,n_context,role='query'):", 'Select target-position states for the requested context or query role while preserving row identity.'), ('scatter_fold_embeddings', 'query_embeddings_l065_v2', 'def scatter_fold_embeddings(n_rows,folds,extractor):', 'Extract each held-out fold as unlabeled queries and scatter its vectors to the original row order.'), ('concatenate_layers', 'query_embeddings_l065_v2', 'def concatenate_layers(embeddings,layers):', 'Join the selected layer representations along the feature axis while retaining rows and layer order.'), ('choose_candidate', 'query_embeddings_l065_v2', 'def choose_candidate(candidates):', 'Choose a head and layer configuration from validation-only candidate scores using a declared deterministic tie rule.')],
66:[('attention_mix', 'tabicl_l066_v2', 'def attention_mix(q,k,v):', 'Compute scaled per-head attention and mix the permitted values.'), ('context_keys', 'tabicl_l066_v2', 'def context_keys(k,v,n_context):', 'Restrict dataset attention memory to labeled context rows.'), ('rotary_pairs', 'tabicl_l066_v2', 'def rotary_pairs(x,freqs):', 'Rotate adjacent query/key coordinate pairs using the stored positional frequencies.'), ('inducing_memory', 'tabicl_l066_v2', 'def inducing_memory(src,inducing,n_context,read_block,write_block):', 'Build inducing summaries from context cells, then let every cell read them.'), ('conditional_affine', 'tabicl_l066_v2', 'def conditional_affine(values,hidden,weight_head,bias_head,weight_norm,bias_norm):', 'Generate and normalize cell-specific scale and offset before applying the scalar value.')],
67:[('neighbor_ids','localpfn_l067_v2','def neighbor_ids(memory,queries,k,memory_ids=None,exclude_ids=None):','Select stable nearest neighbors after excluding the original anchor identity.'),('episode_indices','localpfn_l067_v2','def episode_indices(neighbors,context_size,rng):','Shuffle retrieved neighborhoods and split disjoint shared-context training episodes.'),('local_normalize','localpfn_l067_v2','def local_normalize(x,context_size,max_features=100):','Pad and arrange the pretrained input, fit source-matched local moments, then scale active features.'),('query_loss','localpfn_l067_v2','def query_loss(logits,targets,classes):','Optimize only query targets on the fixed training class axis.'),('validation_choice','localpfn_l067_v2','def validation_choice(scores):','Select the earliest maximum validation AUC, including the frozen checkpoint.')],
68:[('normalize_time', 'driftpfn_l068_v2', 'def normalize_time(c,n):', 'Normalize temporal domains from the labeled context and preserve bounded future extrapolation.'), ('time2vec', 'driftpfn_l068_v2', 'def time2vec(c,weight,bias):', 'Apply the released learned affine coordinate and 99 sine coordinates.'), ('shifted_weights', 'driftpfn_l068_v2', 'def shifted_weights(base,edge_to_relation,selected,shifts):', 'Map selected causal relationships to their functional edges and apply correlated temporal shifts.'), ('temporal_split', 'driftpfn_l068_v2', 'def temporal_split(domains,source_count,seed,cap_per_domain=None):', 'Build label-blind source context, source holdout and strictly future query sets.'), ('dataset_summary', 'driftpfn_l068_v2', 'def dataset_summary(records):', 'Summarize repeated measurements within each dataset without counting rows as independent experiments.')],
69:[('open_class_loss','foundation_core','def open_class_loss(labels, probabilities, classes, epsilon=1e-12):','Score all required labels with a disclosed epsilon for unsupported classes; preserve class/probability alignment.'),('corrupt_column','foundation_core','def corrupt_column(train, test, column, mode):','Create a non-mutating missing/scale test intervention using a training-derived center.')],
70:[('choose_validation','benchmark_core','def choose_validation(errors):','Keep final model choice independent of test labels.'),('paired_summary','benchmark_core','def paired_summary(records):','Implement complete crossed-panel checking, seed-first aggregation, rank statistics and conditional intervals.')],
}
