"""Idempotent integration; does not mark learner mastery."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1];SLUG='0076-encoder-predictor-stack';TITLE='Encoder → predictor: the relational stack'
p=ROOT/'lessons/manifest.json';m=json.loads(p.read_text())
if not any(x['id']==76 for x in m['lessons']):
 m['lessons'].append({'id':76,'slug':SLUG,'year':2,'quarter':4,'checkpoint':False,'labPath':'labs/'+SLUG+'.ipynb','title':TITLE,'published':True});m['version']+=1;p.write_text(json.dumps(m,indent=2)+'\n')
p=ROOT/'notebooks.html';s=p.read_text()
if f'lessons/{SLUG}.html' not in s:
 s=s.replace('<ul class="nb-gallery">',f'<ul class="nb-gallery"><li id="lab-76"><div class="nb-head"><span class="num">Lesson 0076</span><span class="title">{TITLE}</span></div><div class="nb-links"><a href="labs/html/{SLUG}.html">Read lab</a><a href="labs/{SLUG}.ipynb" download>Download notebook</a><a href="lessons/{SLUG}.html">Lesson</a></div></li>',1);p.write_text(s)
p=ROOT/'.github/workflows/pages.yml';s=p.read_text()
if '# L076 stack' not in s:
 s=s.replace('          # L075 PyTorch Frame','          # L076 stack evidence and historical replay contract.\n          cp labs/_verify_l076_results.json labs/_execution_l076_results.json labs/_browser_l076_results.json labs/_sources_l076.json labs/_replay_l076_preflight.json labs/l076-reproduction.md public/labs/\n          cp labs/_replay_l076.py labs/requirements-l076-replay.txt public/labs/\n          # L075 PyTorch Frame',1);p.write_text(s)
p=ROOT/'assets/retrieval-pool.js';s=p.read_text()
if 'l076-routing' not in s:
 item={'id':'l076-routing','lesson':76,'quarter':'Q4','concept':'relational-identity','question':'Customer rows are reordered. What preserves event-to-customer messages?','options':[{'label':'Remap foreign keys into positions','value':'remap'},{'label':'Reuse old destination row positions','value':'reuse'},{'label':'Replace foreign keys with amounts','value':'amount'}],'correct':'remap','explain':'Primary keys identify entities; tensor positions depend on current ordering. Rebuild destinations so messages follow identities.'}
 s=s.replace('global.RETRIEVAL_POOL = [','global.RETRIEVAL_POOL = [\n'+json.dumps(item,indent=2)+',',1);p.write_text(s)
for name,marker,extra in [
 ('NOTES.md','Lesson 076 created','\n## Lesson 076 created · encoder → predictor stack\n\nComplete Frame0.3.0 two-table composition with three live TODOs, exact mean/gradient oracle, future fit/output intervention and identity tests. Four-row overfit diagnostic only; no held-out claim. Historical RelBench Table6 rel-f1 driver-dnf replay includes full archived model/trainer, source pin, protocol audit and isolated CLI/Colab/Modal operators. Local historical preflight blocked by missing/incompatible runtime; full benchmark NOT_RUN. User reiterated full reproduction where possible. No learner completion inferred.\n'),
 ('RESOURCES.md','L076 relational stack','\n## L076 relational stack\n\n- [PyTorch Frame v2, Figure1 and §3](https://arxiv.org/html/2404.00776v2): typed table-to-row interface.\n- [RelBench v1, Table6 and AppendixB](https://arxiv.org/html/2407.20060v1): driver-dnf target and training protocol.\n- [Publication-day source](https://github.com/snap-stanford/relbench/tree/5894184f3d1b2432feb9a208a8aaf18b106fbdf4): original model, neural layers and gnn_node trainer.\n'),
 ('labs/README.md','L076:',f'\n- L076: [Encoder → predictor stack]({SLUG}.ipynb) — full two-table teaching composition; separate historical RelBench replay and explicit NOT_RUN ledger.\n'),
 ('labs/data/README.md','L076 two-table','\n## L076 two-table fixture\n\nTierC generated by `relkit/stack_l076.py`: four customers, five events, noncontiguous keys and two excluded records. Fixed cutoff10; arbitrary diagnostic labels; no benchmark accuracy claim. Optional release replay uses original rel-f1 task data with upstream hashes, no substituted toy dataset. Dataset download/training NOT_RUN locally.\n'),
 ('thesis-dossier.md','L076 |','\n| L076 | BAR | Executed real Frame encoders → explicit eligible one-hop mean → binary head, with identity, fit-scope and gradient checks. Demonstrates the integration interface, not relational predictive advantage. Historical RelBench driver-dnf replay packaged; benchmark NOT_RUN due to historical runtime prerequisites. |\n')]:
 p=ROOT/name;s=p.read_text()
 if marker not in s:p.write_text(s+extra)
p=ROOT/'reference/glossary.html';s=p.read_text()
if 'id="rdl-stack"' not in s:
 s=s.replace('</article>','<section id="rdl-stack"><h2>Relational encoder–predictor stack</h2><p><strong>Message passing:</strong> related records exchange representations along allowed edges. <strong>Aggregation:</strong> reduction of a variable-size neighbor set to a fixed-width vector. <strong>Prediction cutoff:</strong> time at which information must have been available. <strong>Availability time:</strong> when a value becomes accessible, distinct from event time. <strong>Destination index:</strong> receiver position in the current tensor ordering, derived from record identity.</p></section></article>');p.write_text(s)
print('Integrated L076 artifacts; no learner completion recorded')
