"""Register prepared checkpoint; preserve learner status and manifest-driven home navigation."""
from pathlib import Path
import json,re
R=Path(__file__).resolve().parents[1];P=R/'labs';S='0100-heterogeneous-gnn-checkpoint';T='Heterogeneous GNN checkpoint'
p=R/'lessons/manifest.json';d=json.loads(p.read_text())
if not any(x['id']==100 for x in d['lessons']):
 d['lessons'].append({'id':100,'slug':S,'year':3,'quarter':2,'checkpoint':True,'labPath':f'labs/{S}.ipynb','title':T,'published':True});d['version']+=1;p.write_text(json.dumps(d,indent=2)+'\n')
for name in ['index.html','notebooks.html']:
 p=R/name;s=p.read_text();s=re.sub(r'(name="rdl-manifest-version" content=")\d+',r'\g<1>'+str(d['version']),s)
 if name=='notebooks.html' and 'id="lab-100"' not in s:
  s=s.replace('<ul class="nb-gallery">',f'<ul class="nb-gallery"><li id="lab-100"><div class="nb-head"><span class="num">Lesson0100</span><span class="title">{T}</span></div><div class="nb-links"><a href="labs/html/{S}.html">Read lab</a><a class="lab-access-primary" href="https://colab.research.google.com/github/Avistian/relational/blob/main/labs/{S}.ipynb">Run in Colab</a><a download="" href="labs/{S}.ipynb">Download notebook</a><a href="lessons/{S}.html">Lesson</a></div></li>',1)
 p.write_text(s)
p=R/'CURRICULUM.md';p.write_text(p.read_text().replace('| 100 | **Q2 checkpoint** | Schlichtkrull + Hu 2020 | Hetero GNN on 3+ node types |',f'| 100 | [**Q2 checkpoint**](lessons/{S}.html) | Schlichtkrull + Hu 2020 | [Three-type native mini-batching, 24-fit comparison and defense](labs/{S}.ipynb) |'))
p=R/'plan/year-3.md';p.write_text(p.read_text().replace('### 100 · **Q2 checkpoint** — *Schlichtkrull + Hu 2020 · Deliverable-based*',f'### 100 · [**Q2 checkpoint**](../lessons/{S}.html) — *Schlichtkrull + Hu 2020 · Deliverable-based*\n- **Prepared package** — [lab](../labs/{S}.ipynb), [protocol](../labs/l100-reproduction.md): all24 native mini-batched ACM fits, all-neighbor output/gradient audits and fresh ten-run AIFB port. HGT CS NOT_RUN; full-paper parity NOT_ESTABLISHED. Learner defense pending.'))
entries={
'NOTES.md':'\n## Lesson100 created · Heterogeneous GNN checkpoint · 2026-09-20\n\nUser approved integrated checkpoint and reiterated full reproduction. Complete three-type ACM native mini-batched comparison:24fits,960epochs,3840updates, identical sampled-edge schedules across arms/rates, full traces/checkpoints/predictions. All-neighbor typed-ID/output/gradient audits, seed-only loss and correct incomplete-batch weighting. HGT88.810%, uniform87.107%, MLP70.960%, R-GCN49.539% majority collapse retained. Fresh full ten-run AIFB port95.833%; HGT CS full training NOT_RUN, full-paper parity NOT_ESTABLISHED. Complete named-lane implementations visible in notebook appendices. No learner mastery or publication inferred.\n',
'RESOURCES.md':'\n## Lesson 100 · Integrated heterogeneous checkpoint\n\n- [R-GCN, Eq2 and Table2](https://arxiv.org/abs/1703.06103v4): relation-wise message normalization; separate full AIFB release-protocol replay.\n- [HGT, §3 and Table2](https://arxiv.org/abs/2003.01332v1): typed attention, temporal encoding and HGSampling; source-era differences retained.\n- [Native NeighborLoader](https://pytorch-geometric.readthedocs.io/en/latest/modules/loader.html#torch_geometric.loader.NeighborLoader): typed seed prefix, local/global IDs and directional neighborhoods. Executed wrapper/source hashes archived.\n- [L100 full reproduction ledger](labs/l100-reproduction.md): frozen24-fit course protocol, complete AIFB replay and unrun CS full-setting track.\n',
'labs/README.md':f'\n### Lesson100 · Heterogeneous checkpoint\n\n[Student]({S}.ipynb) · [Solution](solutions/{S}.ipynb) · [Read lab](html/{S}.html) · [Protocol](l100-reproduction.md). Native3-type ACM experiment,24fits, typed-ID and gradient audits, three live tasks and written defense. Full visible AIFB/CS appendices; CS training NOT_RUN.\n',
'thesis-dossier.md':'\n- **L100 · BAR · 2026-09-20:** Native heterogeneous sampling passes typed-ID, seed-only loss and fixed-weight full-neighbor gradient audits; all24 matched ACM fits execute. HGT exceeds its uniform ablation by1.70pp under this protocol, while R-GCN collapses to the majority class. One graph/split and a failed optimization trajectory cannot rank families universally. Named AIFB replay is close; full HGT CS/full-paper reproduction remains unestablished.\n'}
for name,entry in entries.items():
 p=R/name;s=p.read_text()
 if entry.strip().splitlines()[0] not in s:p.write_text(s+entry)
p=R/'assets/retrieval-pool.js';s=p.read_text();item={'id':'l100-gradient-update','lesson':100,'quarter':'Q2','concept':'batch-gradient-parity','question':'All-neighbor batches match seed logits. When do their gradients recover the full mean-loss gradient?','options':[{'label':'Weighted accumulation before any update','value':'fixed'},{'label':'Equal accumulation after every update','value':'update'},{'label':'Weighted accumulation after every update','value':'both'}],'correct':'fixed','explain':'At fixed weights, multiply each batch-mean gradient by its fraction of total seeds. Sequential updates change parameters and optimizer state.'}
if item['id'] not in s:s=s.replace('];\n})(window);',', '+json.dumps(item)+'\n];\n})(window);');p.write_text(s)
p=R/'reference/glossary.html';s=p.read_text()
if 'checkpoint-l100' not in s:s=s.replace('</body>','<section id="checkpoint-l100"><h2>Checkpoint contracts · L100</h2><dl><dt>Gradient accumulation</dt><dd>Adding batch gradients at fixed parameters before an optimizer step; means require weights proportional to batch seed counts.</dd><dt>Sampling fingerprint</dt><dd>A hash of ordered seed IDs, typed sampled node IDs and restored edge endpoints used to verify equal sampled computations.</dd><dt>Optimizer trajectory</dt><dd>The sequence of parameter and optimizer-state updates; matching a fixed-weight gradient does not establish equality of sequential trajectories.</dd></dl><p><a href="heterogeneous-checkpoint.html">Checkpoint reference</a></p></section></body>');p.write_text(s)
p=R/'.github/workflows/pages.yml';s=p.read_text();marker='          # L099 controlled'
if '# L100 integrated' not in s:s=s.replace(marker,'          # L100 integrated checkpoint, complete evidence and visible reproduction lanes.\n          cp labs/l100-reproduction.md labs/requirements-l100-*.txt labs/_*l100*.json labs/_*l100.py public/labs/\n          mkdir -p public/labs/solutions public/modal\n          cp labs/solutions/0100-heterogeneous-gnn-checkpoint.ipynb public/labs/solutions/\n          cp -r labs/_experiment_l100_results-checkpoints public/labs/\n          cp modal/l100_paper_repro.py public/modal/\n'+marker)
p.write_text(s)
p=P/'reproductions/execution_evidence.json';d=json.loads(p.read_text());r=json.loads((P/'_experiment_l100_results.json').read_text())
d['lesson100']={'date':'2026-09-20','course_experiment':'MEASURED','planned_fits':24,'completed_fits':24,'epochs':960,'optimizer_updates':3840,'source_manifest':'../_sources_l100.json','environment':r['environment'],'implementation_sha256':r['implementation_sha256'],'commands':['.venv/bin/python labs/_verify_l100.py','.venv/bin/python labs/_operators_l100.py','.venv/bin/python labs/_audit_batches_l100.py','.venv/bin/python labs/_run_l100.py','.venv/bin/python labs/_audit_l100.py','.venv/bin/python labs/_paper_l100.py --target aifb','.venv/bin/python labs/_execute_l100.py','.venv/bin/python labs/_delivery_l100.py'],'measured_accuracy':{a:x['accuracy'] for a,x in r['summary'].items()},'aifb':{'runs':10,'mean':.9583333333333333,'historical_parity':'INCOMPARABLE','evidence':'../_paper_l100_aifb_results.json'},'hgt_cs':'NOT_RUN','full_paper_parity':'NOT_ESTABLISHED','rejected_inferences':['Course execution is not a historical paper experiment','Gradient parity is not sequential optimizer-trajectory parity','One graph/split and R-GCN majority collapse cannot establish a universal family ranking','Equal scores do not establish historical provenance'],'learner_status':'PENDING_WRITTEN_DEFENSE','independent_environment_build':'NOT_CHECKED','live_colab':'NOT_CHECKED','deployment':'NOT_CHECKED'}
p.write_text(json.dumps(d,indent=2)+'\n')
print('Registered prepared L100 without advancing learner mastery')
