"""Record only completed measurements; never infer learner mastery or publication."""
import hashlib,json,re
from pathlib import Path
P=Path(__file__).resolve().parent;R=P.parent
paper=json.loads((P/'_paper_l103_results.json').read_text());assert paper['status']=='COMPLETE' and len(paper['records'])==10
checks={name:json.loads((P/f'_{name}_l103_results.json').read_text()) for name in ['check','source_check','audit','selection_check','padding_check','resume_check','restart_audit','comparison_check','execution','delivery']}
assert all(x['status']=='PASS' for x in checks.values())
assert isinstance(paper['original_source_replay'],dict) and paper['original_source_replay']['status']=='PASS'
report={'date':'2026-09-26','status':'COMPLETE_SELECTED_WIKIPEDIA_REPLAY','paper':paper,'comparison':json.loads((P/'_comparison_l103_results.json').read_text()),'checks':checks,'historical_identity':'INCOMPARABLE','full_paper_parity':'NOT_ESTABLISHED','learner_status':'PENDING_WRITTEN_DEFENSE','live_colab':'NOT_CHECKED','deployment':'NOT_CHECKED','commands':['OMP_NUM_THREADS=1 .venv/bin/python labs/_check_l103.py','OMP_NUM_THREADS=1 .venv/bin/python labs/_source_check_l103.py','OMP_NUM_THREADS=1 .venv/bin/python labs/_audit_l103.py','OMP_NUM_THREADS=1 .venv/bin/python labs/_selection_check_l103.py','OMP_NUM_THREADS=1 .venv/bin/python labs/_padding_check_l103.py','OMP_NUM_THREADS=1 .venv/bin/python labs/_verify_l103.py --preset smoke','OMP_NUM_THREADS=1 .venv/bin/python labs/_resume_check_l103.py','OMP_NUM_THREADS=1 .venv/bin/python labs/_compare_l103.py','.venv/bin/modal run --detach modal/l103_paper_repro.py::main --preset paper','.venv/bin/modal run modal/l103_paper_repro.py::source_check','.venv/bin/python labs/_collect_l103.py labs/results/l103/gpu','.venv/bin/python labs/_execute_l103.py','.venv/bin/python labs/_delivery_l103.py'],'rejected_evidence':['Source parity is not paper-result reproduction','Short teaching/comparison fits are not the original paper experiment','All-event release test is not a disjoint old-node population','A numerical CLOSE cannot repair protocol differences','Ten seeds are not ten independent datasets','Prepared execution does not establish learner mastery, live Colab or deployment']}
p=P/'reproductions/execution_evidence.json';ledger=json.loads(p.read_text());ledger['lesson_103']=report;p.write_text(json.dumps(ledger,indent=2)+'\n')
a,n=paper['summary']['all'],paper['summary']['new'];epochs=sum(r['epochs_completed'] for r in paper['records'])
notes=f'''\n## Lesson103 created · TGAT · 2026-09-26

Approved combined scope and full reproduction requested. Complete ten-run Wikipedia release replay ({epochs} epochs), all-event AP {a['mean_ap_percent']:.4f}% and new-node AP {n['mean_ap_percent']:.4f}%; numerical verdicts {a['numerical_verdict']}/{n['numerical_verdict']}. Full original-model seed-0 prediction replay and independent all-run metrics pass. Six separate matched one-layer TGAT/TGN fits, three live tasks, 1080 temporal oracle cases, exact current-runtime source output/gradient parity and independent preprocessing/split checks. Released sampler/batch omissions, finite-mask padding and shifted checkpoint index preserved and explained. Historical identity INCOMPARABLE; full-paper parity NOT_ESTABLISHED. Learner status PENDING_WRITTEN_DEFENSE; no publication or live Colab inferred.\n'''
p=R/'NOTES.md';s=p.read_text();s=re.sub(r'\n## Lesson103 created.*?(?=\n## |\Z)','',s,flags=re.S);p.write_text(s+notes)
p=R/'thesis-dossier.md';s=p.read_text();s=re.sub(r'\n- \*\*BAR · L103.*?(?=\n|\Z)','',s);p.write_text(s+f'\n- **BAR · L103 (2026-09-26):** Complete selected TGAT Wikipedia release replay: {a["mean_ap_percent"]:.3f}% all-event / {n["mean_ap_percent"]:.3f}% new-node batch-mean AP. Temporal encoding needs an independent recursive information boundary. Release defects and population differences prevent historical equivalence; the three-seed matched course slice does not establish broad TGAT/TGN superiority or relational-database advantage.\n')
p=R/'plan/year-3.md';s=p.read_text();marker='### 103 · TGAT — *Xu 2020, ◆ `2002.07962`*';delivery=f'\n- **Delivered:** [lesson](../lessons/0103-tgat.html), [lab](../labs/0103-tgat.ipynb), three live tasks and complete ten-run Wikipedia release replay ({epochs} epochs): all-event AP {a["mean_ap_percent"]:.3f}%, new-node AP {n["mean_ap_percent"]:.3f}%; numerical {a["numerical_verdict"]}/{n["numerical_verdict"]}. Separate six-fit matched TGAT/TGN comparison. Exact evidence: [results](../labs/_paper_l103_results.json). Historical identity INCOMPARABLE; full-paper parity NOT_ESTABLISHED.'
start=s.index(marker)+len(marker)
if s[start:].startswith('\n- **Delivered:**'):end=s.index('\n',start+1);s=s[:start]+s[end:]
s=s[:start]+delivery+s[start:];p.write_text(s)
p=R/'docs/plans/2026-09-26-l103-tgat.md';s=p.read_text();s=s.split('\n## Execution checkpoint',1)[0];p.write_text(s+'\n## Execution complete\n\nAll ten declared runs, original-model seed-0 replay, independent prediction metrics, standalone notebook and copied-Pages/browser checks completed. Exact results and identities: `labs/_paper_l103_results.json` and `labs/reproductions/execution_evidence.json`. Deployment and live Colab remain NOT_CHECKED.\n')
print('Recorded L103 evidence, notes, roadmap and thesis boundary')
