"""Record verified L112 evidence while preserving other lesson records."""
import json
from pathlib import Path
P=Path(__file__).resolve().parent;R=P.parent
r=json.loads((P/'evidence/l112/summary.json').read_text());replay=json.loads((P/'_replay_l112_results.json').read_text());assert r['status']=='COMPLETE' and replay['status']=='PASS'
p=P/'reproductions/execution_evidence.json';all_=json.loads(p.read_text());all_['l112']={'status':'COMPLETE_SELECTED_EXPERIMENT','experiment':'OGB v6 Table 6, ogbn-arxiv GCN','fresh_runs':10,'epochs':5000,'summary':r['summary'],'independent_node_predictions':1693430,'original_source_prediction_replay':'EXACT_ALL_TEN','historical_identity':'NOT_ESTABLISHED','full_paper_reproduction':'NOT_ESTABLISHED','learner_status':'PENDING_WRITTEN_DEFENSE','live_colab':'NOT_CHECKED','deployment':'NOT_CHECKED','budget':{'limit_usd':10,'successful_resource_estimate_usd':r['successful_resource_usd'],'other_costs':'Failed pretraining pilot/startup/build/storage NOT_ITEMIZED; conservative total resource ceiling including both pilot timeouts USD1.497312'},'protocol':'labs/l112-reproduction.md','evidence':'labs/evidence/l112/summary.json'};p.write_text(json.dumps(all_,indent=2)+'\n')
p=R/'NOTES.md';s=p.read_text();heading='## Lesson 112 prepared · 2026-09-26'
if heading not in s:
 s+='\n\n'+heading+'\n\n- Approved full selected ogbn-arxiv GCN reproduction completed: ten fresh runs × 500 epochs. Test 71.8480% ± 0.3119 pp; validation 73.1041% ± 0.0977 pp; both means CLOSE under predeclared 0.5 pp tolerance.\n- All 1,693,430 final node predictions independently scored and replayed through original GCN code with zero class mismatches; canonical versus original CPU log-probabilities exactly equal. Official loader arrays/splits exact. Native-CSR replay adapter double-loop error fixed and independently regression-checked; training/checkpoints unchanged. Historical identity/full-paper parity NOT_ESTABLISHED.\n- Visible model/trainer, standalone student/executed solution, three live tasks, four rejected mutants, three portable figures, reference and protocol ledger. Learner PENDING_WRITTEN_DEFENSE. Live Colab/deployment NOT_CHECKED.\n- Successful pilot plus ten-run resource estimate USD0.2087; failed pretraining checker attempt and overhead unitemized. Conservative resource ceiling including both pilot timeout allowances USD1.497312, within USD10 plan. See labs/l112-reproduction.md.\n';p.write_text(s)
p=R/'thesis-dossier.md';s=p.read_text();entry='- **BAR · L112 (2026-09-26):** Full selected ogbn-arxiv GCN reproduction: ten fresh 500-epoch fits, test 71.8480% ± 0.3119 pp versus published 71.74% ± 0.29 pp (CLOSE); all final node classes replay exactly through original GCN. This trains on the complete transductive feature graph with a year-based label split; it does not establish point-in-time deployment validity or relational superiority on database tasks. Historical identity and full-paper parity remain NOT_ESTABLISHED.'
if '**BAR · L112' not in s:p.write_text(s+'\n'+entry+'\n')
print('Recorded L112; learner remains PENDING_WRITTEN_DEFENSE')
