repos:
  - repo: https://github.com/psf/black
    # Use `pre-commit autoupdate` to update this automatically
    # If updating, please also update the tag in `requirements-release.txt`
    # and in `.github/workflows/main.yml`
    rev:  23.11.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v3.1.0'
    hooks:
      - id: no-commit-to-branch
        args: ['--branch', 'main']
