"use strict";

// RelBench leaderboard, ported to the Stanford Tabular and Relational Project site.
// Board structure is defined in BOARDS below (the leaderboard repo holds no board metadata).
// Entries are read live from the GitHub leaderboard repo: a single leaderboard.json holds
// an array of methods, each
//   {name,in_context,url,note,date,boards:{<boardKey>:{results:{task:val},mean,cov}}}
// merged into the matching board's rows as {name,in_context,url,note,date,results,mean,cov}.
//
// Layout:
//   1. Board tabs (#splits) — Regression / Classification / Recommendation. The metrics
//      are incompatible, so each task family is a separate top-level board.
// Only full-coverage entries (every task of the board reported; row.mean != null) are
// shown. Ranked by the board mean; click any numeric header to re-rank.
(function () {

  // UI labels (the source site kept these in a shared content module).
  const C = {
    inContext: "In-context",
    cols: { rank: "#", name: "Name", inContext: "In-context", mean: "Mean", submitted: "Submitted" },
    entriesWord: "entries",
    tasksWord: "tasks",
  };

  // The RelBench repo holds only bot-written entries (no board metadata). Board structure
  // is defined here; leaderboard/leaderboard.json (regenerated by the publish workflow
  // from leaderboard/entries/) is read live. If GitHub is unreachable the board shows an
  // error linking to the repo.
  const SRC = {
    repo: "stanford-star/relbench",
    branch: "main",
  };
  const jsonUrl = `https://raw.githubusercontent.com/${SRC.repo}/${SRC.branch}/leaderboard/leaderboard.json`;

  // Board structure (config). Each board's rows are populated from the validator's entries.
  // Tasks listed in order of training-set size (fewest rows first).
  const BOARDS = [
    { key: "regression", label: "Regression", metric: "Normalized mean absolute error (nMAE %)", higher_is_better: false,
      tasks: ["rel-avito/ad-ctr", "rel-f1/driver-position", "rel-event/user-attendance", "rel-trial/study-adverse",
        "rel-trial/site-success", "rel-stack/post-votes", "rel-amazon/item-ltv", "rel-amazon/user-ltv", "rel-hm/item-sales"] },
    { key: "binary_classification", label: "Classification", metric: "Area under the ROC curve (AUROC %)", higher_is_better: true,
      tasks: ["rel-f1/driver-top3", "rel-event/user-repeat", "rel-f1/driver-dnf", "rel-trial/study-outcome",
        "rel-event/user-ignore", "rel-avito/user-clicks", "rel-avito/user-visits", "rel-stack/user-engagement",
        "rel-amazon/item-churn", "rel-stack/user-badge", "rel-hm/user-churn", "rel-amazon/user-churn"] },
    { key: "recommendation", label: "Recommendation", metric: "Mean average precision (MAP %)", higher_is_better: true,
      tasks: ["rel-f1/driver-circuit-compete", "rel-stack/post-post-related", "rel-stack/user-post-comment",
        "rel-trial/condition-sponsor-run", "rel-avito/user-ad-visit", "rel-trial/site-sponsor-run",
        "rel-amazon/user-item-review", "rel-amazon/user-item-rate", "rel-hm/user-item-purchase", "rel-amazon/user-item-purchase"] },
  ];

  const isInContext = (r) => r.in_context === true;

  const state = {
    splits: null,
    active: 0,            // board index
    rankBy: "_mean",      // ranking column key
    showTasks: false,     // per-task columns shown
  };

  const $ = (s) => document.querySelector(s);
  const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;")
    .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const split = () => state.splits[state.active];
  // Task keys are "<db>/<table>" — break after the slash so the header wraps below.
  const brTask = (s) => s.split("/").map(esc).join("<br>");

  // AUROC / MAP shown ×100 (one decimal); regression (NMAE) keeps natural scale.
  const fmtVal = (v) => v == null ? "–" : (v * 100).toFixed(1);

  // Full-coverage entries only (report every task of the board, so mean is defined).
  const fullRows = () => split().rows.filter((r) => r.mean != null);
  const visibleRows = () => fullRows();

  // Live read from GitHub: one fetch of leaderboard.json (an array of entries), merged into
  // each split's `rows` by the entry's board key.
  async function loadEntries() {
    const splits = BOARDS.map((s) => ({ ...s, rows: [] }));
    const byKey = Object.fromEntries(splits.map((s) => [s.key, s]));

    // leaderboard.json may not exist yet (empty leaderboard) — a 404 is not an error;
    // a thrown fetch (GitHub unreachable) propagates and shows the error state.
    const res = await fetch(jsonUrl);
    const entries = res.ok ? await res.json() : [];

    for (const e of entries) {
      if (!e || !e.boards) continue;
      const { boards: eb, ...top } = e;
      for (const [k, b] of Object.entries(eb)) {
        const s = byKey[k]; if (!s) continue;
        s.rows.push({ ...top, results: b.results, mean: b.mean, cov: b.cov });
      }
    }
    return splits;
  }

  async function init() {
    const mount = $("#lb"); if (!mount) return;
    try {
      state.splits = await loadEntries();
    } catch (e) {
      const empty = $("#empty");
      empty.hidden = false;
      empty.innerHTML = "Could not load the leaderboard. View the data on "
        + `<a href="https://github.com/${SRC.repo}" target="_blank" rel="noopener">GitHub ↗</a>.`;
      return;
    }
    renderTabs();
    selectSplit(Math.max(0, boardFromHash()));
    bind();
  }

  // Each board has its own URL (#regression, #classification, #recommendation) so a
  // reload keeps the board and a board can be linked to directly.
  const slug = (s) => s.label.toLowerCase();
  const boardFromHash = () => state.splits.findIndex((s) => slug(s) === location.hash.slice(1).toLowerCase());

  function renderTabs() {
    $("#splits").innerHTML = state.splits.map((s, i) =>
      `<a class="tab" role="tab" href="#${slug(s)}" data-i="${i}" aria-selected="${i === state.active}" aria-controls="lb-panel">${esc(s.label)}`
      + `<small>${s.tasks.length} ${C.tasksWord}</small></a>`).join("");
  }

  // Switching board resets the mean ranking.
  function selectSplit(i) {
    state.active = i;
    state.rankBy = "_mean";
    document.querySelectorAll("#splits .tab").forEach((b) =>
      b.setAttribute("aria-selected", +b.dataset.i === i));
    const h = `#${slug(split())}`;
    if (location.hash !== h) history.replaceState(null, "", h);
    render();
  }

  function bind() {
    $("#task-hint").addEventListener("click", toggleTasks);
    window.addEventListener("hashchange", () => {
      const i = boardFromHash(); if (i >= 0 && i !== state.active) selectSplit(i);
    });
    $("#splits").addEventListener("click", (e) => {
      const b = e.target.closest(".tab"); if (!b) return;
      e.preventDefault();
      history.pushState(null, "", b.getAttribute("href"));
      selectSplit(+b.dataset.i);
    });
    window.addEventListener("popstate", () => {
      const i = boardFromHash(); if (i >= 0 && i !== state.active) selectSplit(i);
    });
  }

  // Column model: # · Name · In-context · Mean · Submitted · one column per task (by train size).
  function columns() {
    const s = split();
    return [
      { key: "_rank", type: "rank", label: C.cols.rank, sticky: true },
      { key: "_name", type: "name", label: C.cols.name, sticky: true },
      { key: "in_context", type: "flag", label: C.cols.inContext },
      { key: "_mean", type: "num", label: C.cols.mean, hib: s.higher_is_better },
      { key: "date", type: "date", label: C.cols.submitted, hib: true },
      ...(state.showTasks ? s.tasks : []).map((t, i) => ({ key: t, type: "num", task: true, first: i === 0, label: brTask(t), hib: s.higher_is_better })),
    ];
  }

  // Rows for the current board × filter, ranked by state.rankBy (missing values sink).
  function viewRows() {
    const rows = visibleRows().map((r) => ({ ...r, _mean: r.mean }));
    const col = columns().find((c) => c.key === state.rankBy) || { hib: split().higher_is_better };
    const get = (r) => state.rankBy === "_mean" ? r._mean
      : state.rankBy === "date" ? r.date
        : r.results[state.rankBy];
    rows.sort((a, b) => {
      const va = get(a), vb = get(b);
      if (va == null && vb == null) return 0;
      if (va == null) return 1;
      if (vb == null) return -1;
      if (typeof va === "string" || typeof vb === "string")   // ISO dates sort lexically
        return col.hib === false ? String(va).localeCompare(String(vb)) : String(vb).localeCompare(String(va));
      return col.hib === false ? va - vb : vb - va;
    });
    return rows.map((r, i) => ({ ...r, _rank: i + 1 }));
  }

  function render() {
    const cols = columns();
    const rows = viewRows();

    const cap = $("#board").querySelector("caption");
    if (cap) cap.textContent = `${split().label} leaderboard`;
    $("#metric").textContent = `${split().metric}, ${split().higher_is_better ? "higher" : "lower"} is better.`;

    // Best value per numeric column (tasks and mean) among visible rows (bolded).
    const best = {};
    for (const c of cols) {
      if (c.type !== "num") continue;
      const vals = rows.map((r) => c.task ? r.results[c.key] : r[c.key]).filter((v) => v != null);
      if (vals.length) best[c.key] = split().higher_is_better ? Math.max(...vals) : Math.min(...vals);
    }

    const numCols = cols.filter((c) => c.type === "num").length;

    const maxLen = Math.max(...split().tasks.map((t) => Math.max(...t.split("/").map((p) => p.length))));
    $("#board").style.setProperty("--task-w", `calc(${maxLen}ch + 22px)`);
    const head = $("#board").querySelector("thead");
    head.innerHTML = "<tr>" + cols.map((c) => {
      // Ranking only means something when there is more than one numeric column to rank
      // by. With just the mean, clicking it re-ranks by the column already in use, so the
      // header stays inert rather than advertising an interaction that does nothing.
      const sortable = c.type === "num" && numCols > 1;
      const active = c.key === state.rankBy;
      const ranked = active ? " ranked" : "";
      const dir = c.hib === false ? "ascending" : "descending";
      const a11y = sortable ? ` role="button" tabindex="0" aria-sort="${active ? dir : "none"}"` : "";
      // The ranked column carries an arrow for the direction that ranks first: up for
      // AUROC / mAP (higher is better), down for nMAE.
      const better = c.hib === false ? " lower-better" : " higher-better";
      const cls = [c.sticky ? "sticky" : "", c.type === "flag" ? "flag" : "", c.type === "date" ? "attr" : "",
        c.task ? "task" : "", c.first ? "first-task" : "",
        sortable ? "rankable" : "", ranked.trim(), better.trim()].filter(Boolean).join(" ");
      const label = c.task ? c.label : `&nbsp;<br>${c.label}`;
      return `<th scope="col" data-key="${esc(c.key)}" class="${cls}"${a11y}>${label}</th>`;
    }).join("") + "</tr>";

    const rank = (th) => {
      const col = cols.find((c) => c.key === th.dataset.key);
      if (!col || col.type !== "num" || numCols < 2) return;
      state.rankBy = col.key;
      render();
    };
    head.onclick = (e) => { const th = e.target.closest("th"); if (th) rank(th); };
    head.onkeydown = (e) => {
      if (e.key !== "Enter" && e.key !== " ") return;
      const th = e.target.closest("th"); if (!th || !th.classList.contains("rankable")) return;
      e.preventDefault();
      rank(th);
    };

    $("#board").querySelector("tbody").innerHTML = rows.map((r) => "<tr>" + cols.map((c) => {
      switch (c.type) {
        case "rank": {
          const medal = r._rank <= 3 ? ` medal-${r._rank}` : "";
          return `<td class="sticky rank${medal}">${r._rank}</td>`;
        }
        case "name": {
          // Link the name to its url if provided; else plain text. The submitter's note,
          // if any, is the hover tooltip (the submission form promises it is shown on hover).
          const name = r.url
            ? `<a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.name)}`
              + `<span class="ext" aria-hidden="true">\u2197</span></a>`
            : esc(r.name);
          // The note is a styled tooltip rather than a native `title`: the name is an <a>,
          // so a title on the wrapper only surfaced after the browser's ~1s delay, and
          // never at all once the pointer sat on the link itself in some browsers.
          const noteText = r.note ? String(r.note).replace(/\r\n?/g, "\n").trim() : "";
          const note = noteText ? ` data-note="${esc(noteText)}" tabindex="0"` : "";
          const cls = noteText ? "m-name has-note" : "m-name";
          return `<td class="sticky name"><span class="${cls}"${note}>${name}</span></td>`;
        }
        case "flag": {
          const yes = isInContext(r);
          const label = yes ? C.inContext : `Not ${C.inContext.toLowerCase()}`;
          return `<td class="flag ${yes ? "yes" : "no"}" title="${esc(label)}">`
            + `<span aria-hidden="true">${yes ? "\u2713" : "\u2717"}</span>`
            + `<span class="sr-only">${esc(label)}</span></td>`;
        }
        case "date": {
          const ranked = c.key === state.rankBy ? " ranked" : "";
          return `<td class="attr${ranked}">${r.date ? esc(String(r.date).slice(0, 10)) : "–"}</td>`;
        }
        default: {   // num
          const v = c.task ? r.results[c.key] : r[c.key];
          const cls = [
            c.key === state.rankBy ? "ranked" : "",
            v != null && v === best[c.key] ? "best" : "",
            c.task ? "task" : "", c.first ? "first-task" : "",
          ].filter(Boolean).join(" ");
          if (c.key === "_mean") return `<td class="${cls} score">${fmtVal(v)}</td>`;
          return `<td class="${cls}">${fmtVal(v)}</td>`;
        }
      }
    }).join("") + "</tr>").join("");

    const empty = rows.length === 0;
    $("#lb .table-wrap").hidden = empty;
    updateHint();
    applyFixedWidths();
    $("#empty").hidden = !empty;
    $("#count").textContent = `${rows.length} ${C.entriesWord}`;
  }

  function updateHint() {
    const hint = $("#task-hint"); if (!hint) return;
    requestAnimationFrame(() => {
      const r = $("#board").getBoundingClientRect();
      const need = state.showTasks ? Math.ceil(r.right + window.scrollX + 28) : 0;
      document.body.style.minWidth = need > window.innerWidth ? `${need}px` : "";
    });
    hint.innerHTML = state.showTasks
      ? `<span aria-hidden="true">&larr;</span> hide task-wise results`
      : `task-wise results <span aria-hidden="true">&rarr;</span>`;
    hint.setAttribute("aria-expanded", state.showTasks);
    $("#board").classList.toggle("with-tasks", state.showTasks);
  }

  // Expanding must not move the existing columns: freeze their collapsed widths, then
  // append the task columns; the table grows past the right margin and the page scrolls.
  function freezeFixedWidths() {
    const ths = [...document.querySelectorAll("#board thead th")];
    state.fixedW = Object.fromEntries(ths.filter((t) => !t.classList.contains("task"))
      .map((t) => [t.dataset.key, t.getBoundingClientRect().width]));
  }

  function applyFixedWidths() {
    for (const t of document.querySelectorAll("#board thead th")) {
      const w = state.showTasks && state.fixedW ? state.fixedW[t.dataset.key] : null;
      t.style.width = w ? `${w}px` : "";
      t.style.minWidth = w ? `${w}px` : "";
    }
  }

  function toggleTasks() {
    if (!state.showTasks) freezeFixedWidths();
    state.showTasks = !state.showTasks;
    if (!state.showTasks && state.rankBy !== "_mean" && state.rankBy !== "date") state.rankBy = "_mean";
    render();
  }

  window.addEventListener("resize", () => {
    if (!state.showTasks) return;
    state.showTasks = false; render(); freezeFixedWidths();
    state.showTasks = true; render();
  });

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();
